package catalogservice
import "example.com/gen_fromdb_sqlite/repository"

// Code generated by microgen. DO NOT EDIT.

// GeneratedRepos groups generated repository dependencies for this service.
type GeneratedRepos struct {
	UserRepo *repository.UserRepository
}
