// Code generated by microgen. DO NOT EDIT.

// Package docs embeds the generated OpenAPI contract.
package docs

import (
	_ "embed"
	"net/http"
)

// OpenAPI is the generated OpenAPI 3.1 document.
//
//go:embed openapi.json
var OpenAPI []byte

// Handler serves the generated OpenAPI document.
func Handler(w http.ResponseWriter, _ *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	_, _ = w.Write(OpenAPI)
}
