// Code generated by microgen. DO NOT EDIT.
package main

import (
	"github.com/gorilla/mux"
	userserviceTransport "example.com/gen_proto_component_flow/transport/userservice"
	"google.golang.org/grpc"
)

func (g generatedServices) generatedRuntime() generatedRuntime {
	rt := generatedRuntime{
		routeEntries: []generatedRouteEntry{
			{Method: "GET", Path: "/getuser", Handler: "GetUser"},
			{Method: "POST", Path: "/createuser", Handler: "CreateUser"},
		},
		httpRegistrars: []func(*mux.Router){
			func(router *mux.Router) {
				userserviceTransport.RegisterHTTPRoutes(router, g.userserviceEndpoints, "")
			},
		},
	}
	rt.grpcRegistrars = []func(*grpc.Server){
		func(server *grpc.Server) {
			userserviceTransport.RegisterGRPCServer(server, g.userserviceEndpoints)
		},
	}
	return rt
}
