// Code generated by microgen. DO NOT EDIT.
package main

import (
	"github.com/gorilla/mux"
	catalogserviceTransport "example.com/gen_fromdb_sqlite/transport/catalogservice"
)

func (g generatedServices) generatedRuntime() generatedRuntime {
	rt := generatedRuntime{
		routeEntries: []generatedRouteEntry{
			{Method: "POST", Path: "/user", Handler: "CreateUser"},
			{Method: "GET", Path: "/user/{id}", Handler: "GetUser"},
			{Method: "PUT", Path: "/user/{id}", Handler: "UpdateUser"},
			{Method: "DELETE", Path: "/user/{id}", Handler: "DeleteUser"},
			{Method: "GET", Path: "/users", Handler: "ListUsers"},
		},
		httpRegistrars: []func(*mux.Router){
			func(router *mux.Router) {
				catalogserviceTransport.RegisterHTTPRoutes(router, g.catalogserviceEndpoints, "")
			},
		},
	}
	return rt
}
