// Code generated by microgen. DO NOT EDIT.
package main

import (
	"example.com/gen_idl_extend_check/model"
	"gorm.io/gorm"
	"net/http"
)

type generatedRouteEntry struct {
	Method  string
	Path    string
	Handler string
}

type generatedRuntime struct {
	routeEntries   []generatedRouteEntry
	httpRegistrars []func(*http.ServeMux)
}

func (rt generatedRuntime) registerRoutes(r *http.ServeMux) {
	for _, register := range rt.httpRegistrars {
		register(r)
	}
}
func (rt generatedRuntime) autoMigrate(db *gorm.DB) error {
	if db == nil {
		return nil
	}
	return db.AutoMigrate(
		&model.User{},
	)
}

func generatedRouteEntries(rt generatedRuntime, customRoutes []generatedRouteEntry, withOpenAPI bool, withSkill bool) []generatedRouteEntry {
	routes := []generatedRouteEntry{
		{Method: "GET", Path: "/health", Handler: "health"},
		{Method: "GET", Path: "/debug/routes", Handler: "debug"},
	}
	routes = append(routes, rt.routeEntries...)
	routes = append(routes, customRoutes...)
	if withOpenAPI {
		routes = append(routes,
			generatedRouteEntry{Method: "GET", Path: "/openapi.json", Handler: "openapi"},
			generatedRouteEntry{Method: "GET", Path: "/schema.json", Handler: "json-schema"},
			generatedRouteEntry{Method: "GET", Path: "/swagger/", Handler: "swagger-ui"},
		)
	}
	if withSkill {
		routes = append(routes, generatedRouteEntry{Method: "GET", Path: "/skill", Handler: "skill"})
	}

	return routes
}
