// Code generated by microgen. DO NOT EDIT.
package main

import (
	"github.com/gorilla/mux"
	"google.golang.org/grpc"
)

type generatedRouteEntry struct {
	Method  string
	Path    string
	Handler string
}

type generatedRuntime struct {
	routeEntries []generatedRouteEntry
	httpRegistrars []func(*mux.Router)
	grpcRegistrars []func(*grpc.Server)
}

func (rt generatedRuntime) registerRoutes(r *mux.Router) {
	for _, register := range rt.httpRegistrars {
		register(r)
	}
}
func (rt generatedRuntime) registerGRPCServices(server *grpc.Server) {
	for _, register := range rt.grpcRegistrars {
		register(server)
	}
}

func generatedRouteEntries(rt generatedRuntime, withSwag bool, withSkill bool) []generatedRouteEntry {
	routes := []generatedRouteEntry{
		{Method: "GET", Path: "/health", Handler: "health"},
		{Method: "GET", Path: "/debug/routes", Handler: "debug"},
	}
	routes = append(routes, rt.routeEntries...)
	if withSwag {
		routes = append(routes, generatedRouteEntry{Method: "GET", Path: "/swagger/", Handler: "swagger-ui"})
	}
	if withSkill {
		routes = append(routes, generatedRouteEntry{Method: "GET", Path: "/skill", Handler: "skill"})
	}
	return routes
}
