package userservice
import "example.com/gen_idl_extend_append_model/repository"

// Code generated by microgen. DO NOT EDIT.

// GeneratedRepos groups generated repository dependencies for this service.
type GeneratedRepos struct {
	UserRepo *repository.UserRepository
	ProductRepo *repository.ProductRepository
}
