// Code generated by microgen. DO NOT EDIT.
package config

// Load preserves the generated public contract:
// defaults -> local YAML -> env overrides -> remote seam.
func Load(path string) (*Config, error) {
	cfg, err := LoadLocal(path)
	if err != nil {
		return nil, err
	}
	if err := ApplyEnv(cfg); err != nil {
		return nil, err
	}
	return LoadRemote(cfg)
}
