// Code generated by microgen. DO NOT EDIT.
package main

import (
	userserviceTransport "example.com/gen_idl_components/transport/userservice"
	"net/http"
)

func (g generatedServices) generatedRuntime() generatedRuntime {
	rt := generatedRuntime{
		routeEntries: []generatedRouteEntry{
			{Method: "POST", Path: "/createuser", Handler: "CreateUser"},
			{Method: "GET", Path: "/getuser", Handler: "GetUser"},
			{Method: "GET", Path: "/listusers", Handler: "ListUsers"},
			{Method: "DELETE", Path: "/deleteuser", Handler: "DeleteUser"},
			{Method: "PUT", Path: "/updateuser", Handler: "UpdateUser"},
			{Method: "GET", Path: "/findbyemail", Handler: "FindByEmail"},
			{Method: "GET", Path: "/searchusers", Handler: "SearchUsers"},
			{Method: "GET", Path: "/querystats", Handler: "QueryStats"},
			{Method: "DELETE", Path: "/removeexpired", Handler: "RemoveExpired"},
			{Method: "PUT", Path: "/editprofile", Handler: "EditProfile"},
			{Method: "PUT", Path: "/modifyemail", Handler: "ModifyEmail"},
			{Method: "PUT", Path: "/patchstatus", Handler: "PatchStatus"},
		},
		httpRegistrars: []func(*http.ServeMux){
			func(router *http.ServeMux) {
				userserviceTransport.RegisterHTTPRoutes(router, g.userserviceEndpoints, "")
			},
		},
	}
	return rt
}
