// Code generated by microgen. DO NOT EDIT.
//
// Package userservicesdk is the client SDK for UserService.
//
// Usage:
//
//	// HTTP
//	client := userservicesdk.New("http://localhost:8080")
//	resp, err := client.CreateUser(ctx, idl.CreateUserRequest{...})
package userservicesdk

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	transporthttp "github.com/dreamsxin/go-kit/v2/transport/http"

	idl "example.com/gen_idl_integration"
)

// ─────────────────────────── Client interface ────────────────────────────────

// Client is the UserService client interface. It mirrors the unary
// methods of the server-side Service interface, so code written against it can
// be tested with a mock. Streaming methods are gRPC-only and live on
// StreamingClient, which embeds this one.
type Client interface {
	// CreateUser - CreateUser creates a new user.
	CreateUser(ctx context.Context, req idl.CreateUserRequest) (idl.CreateUserResponse, error)
	// GetUser - GetUser retrieves a user by ID.
	GetUser(ctx context.Context, req idl.GetUserRequest) (idl.GetUserResponse, error)
	// ListUsers - ListUsers lists all users.
	ListUsers(ctx context.Context, req idl.ListUsersRequest) (idl.ListUsersResponse, error)
	// DeleteUser - DeleteUser removes a user.
	DeleteUser(ctx context.Context, req idl.DeleteUserRequest) (idl.DeleteUserResponse, error)
	// UpdateUser - UpdateUser modifies a user.
	UpdateUser(ctx context.Context, req idl.UpdateUserRequest) (idl.UpdateUserResponse, error)
	// FindByEmail - FindByEmail finds users by email prefix.
	FindByEmail(ctx context.Context, req idl.GetUserRequest) (idl.GetUserResponse, error)
	// SearchUsers - SearchUsers searches users.
	SearchUsers(ctx context.Context, req idl.ListUsersRequest) (idl.ListUsersResponse, error)
	// QueryStats - QueryStats returns statistics.
	QueryStats(ctx context.Context, req idl.GetUserRequest) (idl.GetUserResponse, error)
	// RemoveExpired - RemoveExpired removes expired users.
	RemoveExpired(ctx context.Context, req idl.DeleteUserRequest) (idl.DeleteUserResponse, error)
	// EditProfile - EditProfile edits profile.
	EditProfile(ctx context.Context, req idl.UpdateUserRequest) (idl.UpdateUserResponse, error)
	// ModifyEmail - ModifyEmail modifies email.
	ModifyEmail(ctx context.Context, req idl.UpdateUserRequest) (idl.UpdateUserResponse, error)
	// PatchStatus - PatchStatus patches status.
	PatchStatus(ctx context.Context, req idl.UpdateUserRequest) (idl.UpdateUserResponse, error)
}

// ─────────────────────────── HTTP Constructor ────────────────────────────────

// Option configures the HTTP client.
type Option func(*httpClient)

const defaultMaxResponseBodyBytes int64 = 4 << 20

// WithTimeout sets the per-request timeout for unary calls (default: 30s).
// A non-positive value is ignored and the default is kept.
//
// It is applied as a context deadline on each call rather than as
// http.Client.Timeout, so it holds whether or not WithHTTPClient replaced the
// client. Streaming calls are not bounded by it.
func WithTimeout(d time.Duration) Option {
	return func(c *httpClient) {
		if d > 0 {
			c.timeout = d
		}
	}
}

// WithHTTPClient replaces the default *http.Client. A nil client is ignored and
// the default is kept.
func WithHTTPClient(hc *http.Client) Option {
	return func(c *httpClient) {
		if hc != nil {
			c.http = hc
		}
	}
}

// WithMaxResponseBodyBytes caps a single HTTP response body. A non-positive
// value is ignored and the default is kept.
func WithMaxResponseBodyBytes(n int64) Option {
	return func(c *httpClient) {
		if n > 0 {
			c.maxResponseBodyBytes = n
		}
	}
}

// WithHeader adds a static header to every request (e.g. Authorization).
func WithHeader(key, value string) Option {
	return func(c *httpClient) { c.headers[key] = value }
}

// WithBearerToken is a shorthand for WithHeader("Authorization", "Bearer "+token).
func WithBearerToken(token string) Option {
	return WithHeader("Authorization", "Bearer "+token)
}

// WithRequestHook registers a function called before every request.
// Use it to inject dynamic headers (e.g. per-request auth tokens).
func WithRequestHook(fn func(r *http.Request)) Option {
	return func(c *httpClient) { c.hooks = append(c.hooks, fn) }
}

// New creates a UserService HTTP client.
//
// baseURL is the server base URL, e.g. "http://localhost:8080".
func New(baseURL string, opts ...Option) Client {
	c := &httpClient{
		baseURL:              baseURL,
		timeout:              30 * time.Second,
		headers:              make(map[string]string),
		maxResponseBodyBytes: defaultMaxResponseBodyBytes,
	}
	for _, o := range opts {
		o(c)
	}
	if c.http == nil {
		// No Timeout here: the per-request deadline in do covers the whole
		// call including the body read, and applying both would give two
		// bounds that drift apart when WithHTTPClient replaces the client.
		c.http = &http.Client{}
	}
	return c
}

// ─────────────────────────── gRPC Constructor ────────────────────────────────

// ─────────────────────────── HTTP implementation ──────────────────────────────

type httpClient struct {
	baseURL              string
	timeout              time.Duration
	http                 *http.Client
	headers              map[string]string
	hooks                []func(*http.Request)
	maxResponseBodyBytes int64
}

// APIError is returned when the server responds with a non-2xx status.
//
// It satisfies the framework's transport error contracts structurally, without
// importing them, so a service that relays this error from an endpoint gets the
// upstream status and classification instead of a blanket 500:
//
//   - StatusCode reports the upstream status (transporthttp.StatusCoder).
//   - ErrorKindName reports the transport-neutral kind (apperror.KindNamer), so
//     a gRPC hop maps it to the matching code.
//   - PublicMessage reports the status without the body (PublicMessager). Error
//     keeps the body for logs; relaying it verbatim would leak whatever the
//     upstream put there, because the built-in encoders fall back to Error()
//     below 500.
//
// Translate rather than relay when the upstream failure means something else to
// your own callers — an upstream 404 would otherwise make your handler answer
// 404.
type APIError struct {
	Status int
	Body   string
}

func (e *APIError) Error() string {
	return fmt.Sprintf("userservicesdk: server returned %d: %s", e.Status, e.Body)
}

// StatusCode reports the upstream HTTP status.
func (e *APIError) StatusCode() int {
	if e == nil {
		return 0
	}
	return e.Status
}

// PublicMessage reports the upstream status without the upstream body.
func (e *APIError) PublicMessage() string {
	if e == nil {
		return ""
	}
	return fmt.Sprintf("upstream request failed with status %d", e.Status)
}

// ErrorKindName maps the upstream status to the transport-neutral kind name the
// framework uses, so the classification survives another hop in either protocol.
func (e *APIError) ErrorKindName() string {
	if e == nil {
		return ""
	}
	switch e.Status {
	case http.StatusBadRequest:
		return "invalid_argument"
	case http.StatusUnauthorized:
		return "unauthenticated"
	case http.StatusForbidden:
		return "permission_denied"
	case http.StatusNotFound:
		return "not_found"
	case http.StatusConflict:
		return "conflict"
	case http.StatusPreconditionFailed:
		return "failed_precondition"
	case http.StatusTooManyRequests:
		return "resource_exhausted"
	case http.StatusRequestTimeout, http.StatusGatewayTimeout:
		return "deadline_exceeded"
	case http.StatusNotImplemented:
		return "unimplemented"
	case http.StatusServiceUnavailable, http.StatusBadGateway:
		return "unavailable"
	}
	if e.Status >= 400 && e.Status < 500 {
		return "invalid_argument"
	}
	return "internal"
}

// Retryable reports whether the upstream status is generally safe to retry.
func (e *APIError) Retryable() bool {
	if e == nil {
		return false
	}
	switch e.Status {
	case http.StatusRequestTimeout, http.StatusTooManyRequests,
		http.StatusBadGateway, http.StatusServiceUnavailable, http.StatusGatewayTimeout:
		return true
	}
	return false
}

func (c *httpClient) do(ctx context.Context, method, path string, reqBody, respBody interface{}) error {
	if c.timeout > 0 {
		var cancel context.CancelFunc
		ctx, cancel = context.WithTimeout(ctx, c.timeout)
		defer cancel()
	}
	var bodyReader io.Reader
	if reqBody != nil {
		b, err := json.Marshal(reqBody)
		if err != nil {
			return fmt.Errorf("userservicesdk: marshal request: %w", err)
		}
		bodyReader = bytes.NewReader(b)
	}

	requestURL, err := resolveRequestURL(c.baseURL, path)
	if err != nil {
		return fmt.Errorf("userservicesdk: resolve request URL: %w", err)
	}
	req, err := http.NewRequestWithContext(ctx, method, requestURL, bodyReader)
	if err != nil {
		return fmt.Errorf("userservicesdk: build request: %w", err)
	}
	if reqBody != nil {
		req.Header.Set("Content-Type", "application/json; charset=utf-8")
	}
	req.Header.Set("Accept", "application/json")
	for k, v := range c.headers {
		req.Header.Set(k, v)
	}
	for _, hook := range c.hooks {
		hook(req)
	}

	resp, err := c.http.Do(req)
	if err != nil {
		return fmt.Errorf("userservicesdk: send request: %w", err)
	}
	defer resp.Body.Close()

	raw, err := io.ReadAll(io.LimitReader(resp.Body, c.maxResponseBodyBytes+1))
	if err != nil {
		return fmt.Errorf("userservicesdk: read response: %w", err)
	}
	if int64(len(raw)) > c.maxResponseBodyBytes {
		return fmt.Errorf("userservicesdk: response body exceeds %d bytes", c.maxResponseBodyBytes)
	}
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return &APIError{Status: resp.StatusCode, Body: string(raw)}
	}

	if respBody != nil {
		if err := json.Unmarshal(raw, respBody); err != nil {
			return fmt.Errorf("userservicesdk: decode response: %w", err)
		}
	}
	return nil
}

func resolveRequestURL(baseURL, path string) (string, error) {
	base, err := url.Parse(strings.TrimRight(baseURL, "/") + "/")
	if err != nil {
		return "", err
	}
	if base.Scheme == "" || base.Host == "" {
		return "", fmt.Errorf("base URL must include scheme and host")
	}
	reference, err := url.Parse(path)
	if err != nil {
		return "", err
	}
	return base.ResolveReference(reference).String(), nil
}

func buildGETPath(path string, reqBody interface{}) (string, error) {
	return transporthttp.EncodePathAndQuery(path, reqBody)
}

func buildRequestPath(path string, reqBody interface{}) (string, error) {
	return transporthttp.EncodePath(path, reqBody)
}

func (c *httpClient) CreateUser(ctx context.Context, req idl.CreateUserRequest) (idl.CreateUserResponse, error) {
	var resp idl.CreateUserResponse
	path, err := buildRequestPath("/api/idl/userservice/createuser", req)
	if err != nil {
		return resp, fmt.Errorf("encode request path: %w", err)
	}
	err = c.do(ctx, "POST", path, req, &resp)
	return resp, err
}

func (c *httpClient) GetUser(ctx context.Context, req idl.GetUserRequest) (idl.GetUserResponse, error) {
	var resp idl.GetUserResponse
	path, err := buildGETPath("/api/idl/userservice/getuser", req)
	if err != nil {
		return resp, fmt.Errorf("encode GET query: %w", err)
	}
	err = c.do(ctx, "GET", path, nil, &resp)
	return resp, err
}

func (c *httpClient) ListUsers(ctx context.Context, req idl.ListUsersRequest) (idl.ListUsersResponse, error) {
	var resp idl.ListUsersResponse
	path, err := buildGETPath("/api/idl/userservice/listusers", req)
	if err != nil {
		return resp, fmt.Errorf("encode GET query: %w", err)
	}
	err = c.do(ctx, "GET", path, nil, &resp)
	return resp, err
}

func (c *httpClient) DeleteUser(ctx context.Context, req idl.DeleteUserRequest) (idl.DeleteUserResponse, error) {
	var resp idl.DeleteUserResponse
	path, err := buildRequestPath("/api/idl/userservice/deleteuser", req)
	if err != nil {
		return resp, fmt.Errorf("encode request path: %w", err)
	}
	err = c.do(ctx, "DELETE", path, req, &resp)
	return resp, err
}

func (c *httpClient) UpdateUser(ctx context.Context, req idl.UpdateUserRequest) (idl.UpdateUserResponse, error) {
	var resp idl.UpdateUserResponse
	path, err := buildRequestPath("/api/idl/userservice/updateuser", req)
	if err != nil {
		return resp, fmt.Errorf("encode request path: %w", err)
	}
	err = c.do(ctx, "PUT", path, req, &resp)
	return resp, err
}

func (c *httpClient) FindByEmail(ctx context.Context, req idl.GetUserRequest) (idl.GetUserResponse, error) {
	var resp idl.GetUserResponse
	path, err := buildGETPath("/api/idl/userservice/findbyemail", req)
	if err != nil {
		return resp, fmt.Errorf("encode GET query: %w", err)
	}
	err = c.do(ctx, "GET", path, nil, &resp)
	return resp, err
}

func (c *httpClient) SearchUsers(ctx context.Context, req idl.ListUsersRequest) (idl.ListUsersResponse, error) {
	var resp idl.ListUsersResponse
	path, err := buildGETPath("/api/idl/userservice/searchusers", req)
	if err != nil {
		return resp, fmt.Errorf("encode GET query: %w", err)
	}
	err = c.do(ctx, "GET", path, nil, &resp)
	return resp, err
}

func (c *httpClient) QueryStats(ctx context.Context, req idl.GetUserRequest) (idl.GetUserResponse, error) {
	var resp idl.GetUserResponse
	path, err := buildGETPath("/api/idl/userservice/querystats", req)
	if err != nil {
		return resp, fmt.Errorf("encode GET query: %w", err)
	}
	err = c.do(ctx, "GET", path, nil, &resp)
	return resp, err
}

func (c *httpClient) RemoveExpired(ctx context.Context, req idl.DeleteUserRequest) (idl.DeleteUserResponse, error) {
	var resp idl.DeleteUserResponse
	path, err := buildRequestPath("/api/idl/userservice/removeexpired", req)
	if err != nil {
		return resp, fmt.Errorf("encode request path: %w", err)
	}
	err = c.do(ctx, "DELETE", path, req, &resp)
	return resp, err
}

func (c *httpClient) EditProfile(ctx context.Context, req idl.UpdateUserRequest) (idl.UpdateUserResponse, error) {
	var resp idl.UpdateUserResponse
	path, err := buildRequestPath("/api/idl/userservice/editprofile", req)
	if err != nil {
		return resp, fmt.Errorf("encode request path: %w", err)
	}
	err = c.do(ctx, "PUT", path, req, &resp)
	return resp, err
}

func (c *httpClient) ModifyEmail(ctx context.Context, req idl.UpdateUserRequest) (idl.UpdateUserResponse, error) {
	var resp idl.UpdateUserResponse
	path, err := buildRequestPath("/api/idl/userservice/modifyemail", req)
	if err != nil {
		return resp, fmt.Errorf("encode request path: %w", err)
	}
	err = c.do(ctx, "PUT", path, req, &resp)
	return resp, err
}

func (c *httpClient) PatchStatus(ctx context.Context, req idl.UpdateUserRequest) (idl.UpdateUserResponse, error) {
	var resp idl.UpdateUserResponse
	path, err := buildRequestPath("/api/idl/userservice/patchstatus", req)
	if err != nil {
		return resp, fmt.Errorf("encode request path: %w", err)
	}
	err = c.do(ctx, "PUT", path, req, &resp)
	return resp, err
}

// ─────────────────────────── gRPC implementation ──────────────────────────────
