// Code generated by microgen. DO NOT EDIT.
package main

import (
	kitlog "github.com/dreamsxin/go-kit/log"
	"example.com/gen_idl_extend_check/repository"
	userserviceEndpoint "example.com/gen_idl_extend_check/endpoint/userservice"
	userserviceSvc "example.com/gen_idl_extend_check/service/userservice"
)

type generatedServices struct {
	userserviceSvc       userserviceSvc.UserService
	userserviceEndpoints userserviceEndpoint.UserServiceEndpoints
}

func initGeneratedServices(logger *kitlog.Logger, repoDB *repository.DB) generatedServices {
	generated := generatedServices{}

	_ = logger
	_ = repoDB
	userRepo := repository.NewUserRepository(repoDB)
	_ = userRepo
	generated.userserviceSvc = userserviceSvc.NewServiceWithRepo(nil, userserviceSvc.GeneratedRepos{
		UserRepo: userRepo,
	})
	generated.userserviceEndpoints = userserviceEndpoint.MakeServerEndpoints(generated.userserviceSvc, logger)

	return generated
}
