package repository

import (
	"context"
	"errors"
	"fmt"

	"gorm.io/gorm"
	"example.com/gen_idl_default_flags/model"
)

// Code generated by microgen. DO NOT EDIT.

// UserRepository provides generated persistence helpers for User.
type UserRepository struct {
	db *DB
}

// NewUserRepository creates a UserRepository.
func NewUserRepository(db *DB) *UserRepository {
	return &UserRepository{db: db}
}

// Create inserts a new record.
func (r *UserRepository) Create(ctx context.Context, m *model.User) error {
	if err := r.db.WithContext(ctx).Create(m).Error; err != nil {
		return fmt.Errorf("user.Create: %w", err)
	}
	return nil
}

// GetByID loads one record by primary key.
func (r *UserRepository) GetByID(ctx context.Context, id uint) (*model.User, error) {
	var m model.User
	err := r.db.WithContext(ctx).First(&m, id).Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, nil
		}
		return nil, fmt.Errorf("user.GetByID(%d): %w", id, err)
	}
	return &m, nil
}

// Update saves the full record.
func (r *UserRepository) Update(ctx context.Context, m *model.User) error {
	if err := r.db.WithContext(ctx).Save(m).Error; err != nil {
		return fmt.Errorf("user.Update: %w", err)
	}
	return nil
}

// Updates applies a partial update.
func (r *UserRepository) Updates(ctx context.Context, id uint, values map[string]interface{}) error {
	result := r.db.WithContext(ctx).Model(&model.User{}).Where("id = ?", id).Updates(values)
	if result.Error != nil {
		return fmt.Errorf("user.Updates(%d): %w", id, result.Error)
	}
	if result.RowsAffected == 0 {
		return fmt.Errorf("user.Updates(%d): %w", id, ErrNotFound)
	}
	return nil
}

// Delete removes one record.
func (r *UserRepository) Delete(ctx context.Context, id uint) error {
	result := r.db.WithContext(ctx).Delete(&model.User{}, id)
	if result.Error != nil {
		return fmt.Errorf("user.Delete(%d): %w", id, result.Error)
	}
	if result.RowsAffected == 0 {
		return fmt.Errorf("user.Delete(%d): %w", id, ErrNotFound)
	}
	return nil
}

// UserListResult is the generated paged query result for User.
type UserListResult struct {
	Total    int64            `json:"total"`
	Page     int              `json:"page"`
	PageSize int              `json:"page_size"`
	Data     []model.User `json:"data"`
}

// List performs a generated paged query.
func (r *UserRepository) List(ctx context.Context, q PageQuery) (*UserListResult, error) {
	q.normalize()

	db := r.db.WithContext(ctx).Model(&model.User{})

	if q.Keyword != "" {
		kw := "%" + q.Keyword + "%"
		// TODO: Adjust the generated search conditions for your real fields.
		_ = kw
	}

	var total int64
	if err := db.Count(&total).Error; err != nil {
		return nil, fmt.Errorf("user.List count: %w", err)
	}

	order := q.OrderBy
	if q.Desc {
		order += " DESC"
	} else {
		order += " ASC"
	}
	db = db.Order(order)

	offset := (q.Page - 1) * q.PageSize
	db = db.Offset(offset).Limit(q.PageSize)

	var records []model.User
	if err := db.Find(&records).Error; err != nil {
		return nil, fmt.Errorf("user.List query: %w", err)
	}

	return &UserListResult{
		Total:    total,
		Page:     q.Page,
		PageSize: q.PageSize,
		Data:     records,
	}, nil
}
