// Code generated by microgen. DO NOT EDIT.
//
// Package userservicesdk is the client SDK for UserService.
//
// Usage:
//
//	// HTTP
//	client := userservicesdk.New("http://localhost:8080")
//	resp, err := client.CreateUser(ctx, idl.CreateUserRequest{...})
//
//
package userservicesdk

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	transporthttp "github.com/dreamsxin/go-kit/v2/transport/http"

	idl "example.com/gen_idl_rerun"
)

// ─────────────────────────── Client interface ────────────────────────────────

// Client is the UserService client interface.
// It mirrors the server-side Service interface exactly, so any code that
// works against the interface can be tested with a mock.
type Client interface {
	// CreateUser - CreateUser creates a new user.
	CreateUser(ctx context.Context, req idl.CreateUserRequest) (idl.CreateUserResponse, error)
	// GetUser - GetUser retrieves a user by ID.
	GetUser(ctx context.Context, req idl.GetUserRequest) (idl.GetUserResponse, error)
	// ListUsers - ListUsers lists all users.
	ListUsers(ctx context.Context, req idl.ListUsersRequest) (idl.ListUsersResponse, error)
	// DeleteUser - DeleteUser removes a user.
	DeleteUser(ctx context.Context, req idl.DeleteUserRequest) (idl.DeleteUserResponse, error)
	// UpdateUser - UpdateUser modifies a user.
	UpdateUser(ctx context.Context, req idl.UpdateUserRequest) (idl.UpdateUserResponse, error)
	// FindByEmail - FindByEmail finds users by email prefix.
	FindByEmail(ctx context.Context, req idl.GetUserRequest) (idl.GetUserResponse, error)
	// SearchUsers - SearchUsers searches users.
	SearchUsers(ctx context.Context, req idl.ListUsersRequest) (idl.ListUsersResponse, error)
	// QueryStats - QueryStats returns statistics.
	QueryStats(ctx context.Context, req idl.GetUserRequest) (idl.GetUserResponse, error)
	// RemoveExpired - RemoveExpired removes expired users.
	RemoveExpired(ctx context.Context, req idl.DeleteUserRequest) (idl.DeleteUserResponse, error)
	// EditProfile - EditProfile edits profile.
	EditProfile(ctx context.Context, req idl.UpdateUserRequest) (idl.UpdateUserResponse, error)
	// ModifyEmail - ModifyEmail modifies email.
	ModifyEmail(ctx context.Context, req idl.UpdateUserRequest) (idl.UpdateUserResponse, error)
	// PatchStatus - PatchStatus patches status.
	PatchStatus(ctx context.Context, req idl.UpdateUserRequest) (idl.UpdateUserResponse, error)
}

// ─────────────────────────── HTTP Constructor ────────────────────────────────

// Option configures the HTTP client.
type Option func(*httpClient)

const defaultMaxResponseBodyBytes int64 = 4 << 20

// WithTimeout sets the per-request HTTP timeout (default: 30s).
func WithTimeout(d time.Duration) Option {
	return func(c *httpClient) { c.timeout = d }
}

// WithHTTPClient replaces the default *http.Client.
func WithHTTPClient(hc *http.Client) Option {
	return func(c *httpClient) { c.http = hc }
}

// WithMaxResponseBodyBytes caps a single HTTP response body.
func WithMaxResponseBodyBytes(n int64) Option {
	return func(c *httpClient) {
		if n > 0 {
			c.maxResponseBodyBytes = n
		}
	}
}

// WithHeader adds a static header to every request (e.g. Authorization).
func WithHeader(key, value string) Option {
	return func(c *httpClient) { c.headers[key] = value }
}

// WithBearerToken is a shorthand for WithHeader("Authorization", "Bearer "+token).
func WithBearerToken(token string) Option {
	return WithHeader("Authorization", "Bearer "+token)
}

// WithRequestHook registers a function called before every request.
// Use it to inject dynamic headers (e.g. per-request auth tokens).
func WithRequestHook(fn func(r *http.Request)) Option {
	return func(c *httpClient) { c.hooks = append(c.hooks, fn) }
}

// New creates a UserService HTTP client.
//
// baseURL is the server base URL, e.g. "http://localhost:8080".
func New(baseURL string, opts ...Option) Client {
	c := &httpClient{
		baseURL:              baseURL,
		timeout:              30 * time.Second,
		headers:              make(map[string]string),
		maxResponseBodyBytes: defaultMaxResponseBodyBytes,
	}
	for _, o := range opts {
		o(c)
	}
	if c.http == nil {
		c.http = &http.Client{Timeout: c.timeout}
	}
	return c
}

// ─────────────────────────── gRPC Constructor ────────────────────────────────

// ─────────────────────────── HTTP implementation ──────────────────────────────

type httpClient struct {
	baseURL              string
	timeout              time.Duration
	http                 *http.Client
	headers              map[string]string
	hooks                []func(*http.Request)
	maxResponseBodyBytes int64
}

// APIError is returned when the server responds with a non-2xx status.
// StatusCode and Body preserve the transport error contract for callers.
type APIError struct {
	StatusCode int
	Body       string
}

func (e *APIError) Error() string {
	return fmt.Sprintf("userservicesdk: server returned %d: %s", e.StatusCode, e.Body)
}

func (c *httpClient) do(ctx context.Context, method, path string, reqBody, respBody interface{}) error {
	var bodyReader io.Reader
	if reqBody != nil {
		b, err := json.Marshal(reqBody)
		if err != nil {
			return fmt.Errorf("userservicesdk: marshal request: %w", err)
		}
		bodyReader = bytes.NewReader(b)
	}

	requestURL, err := resolveRequestURL(c.baseURL, path)
	if err != nil {
		return fmt.Errorf("userservicesdk: resolve request URL: %w", err)
	}
	req, err := http.NewRequestWithContext(ctx, method, requestURL, bodyReader)
	if err != nil {
		return fmt.Errorf("userservicesdk: build request: %w", err)
	}
	if reqBody != nil {
		req.Header.Set("Content-Type", "application/json; charset=utf-8")
	}
	req.Header.Set("Accept", "application/json")
	for k, v := range c.headers {
		req.Header.Set(k, v)
	}
	for _, hook := range c.hooks {
		hook(req)
	}

	resp, err := c.http.Do(req)
	if err != nil {
		return fmt.Errorf("userservicesdk: send request: %w", err)
	}
	defer resp.Body.Close()

	raw, err := io.ReadAll(io.LimitReader(resp.Body, c.maxResponseBodyBytes+1))
	if err != nil {
		return fmt.Errorf("userservicesdk: read response: %w", err)
	}
	if int64(len(raw)) > c.maxResponseBodyBytes {
		return fmt.Errorf("userservicesdk: response body exceeds %d bytes", c.maxResponseBodyBytes)
	}
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return &APIError{StatusCode: resp.StatusCode, Body: string(raw)}
	}

	if respBody != nil {
		if err := json.Unmarshal(raw, respBody); err != nil {
			return fmt.Errorf("userservicesdk: decode response: %w", err)
		}
	}
	return nil
}

func resolveRequestURL(baseURL, path string) (string, error) {
	base, err := url.Parse(strings.TrimRight(baseURL, "/") + "/")
	if err != nil {
		return "", err
	}
	if base.Scheme == "" || base.Host == "" {
		return "", fmt.Errorf("base URL must include scheme and host")
	}
	reference, err := url.Parse(path)
	if err != nil {
		return "", err
	}
	return base.ResolveReference(reference).String(), nil
}

func buildGETPath(path string, reqBody interface{}) (string, error) {
	return transporthttp.EncodePathAndQuery(path, reqBody)
}

func buildRequestPath(path string, reqBody interface{}) (string, error) {
	return transporthttp.EncodePath(path, reqBody)
}

func (c *httpClient) CreateUser(ctx context.Context, req idl.CreateUserRequest) (idl.CreateUserResponse, error) {
	var resp idl.CreateUserResponse
	path, err := buildRequestPath("/createuser", req)
	if err != nil {
		return resp, fmt.Errorf("encode request path: %w", err)
	}
	err = c.do(ctx, "POST", path, req, &resp)
	return resp, err
}

func (c *httpClient) GetUser(ctx context.Context, req idl.GetUserRequest) (idl.GetUserResponse, error) {
	var resp idl.GetUserResponse
	path, err := buildGETPath("/getuser", req)
	if err != nil {
		return resp, fmt.Errorf("encode GET query: %w", err)
	}
	err = c.do(ctx, "GET", path, nil, &resp)
	return resp, err
}

func (c *httpClient) ListUsers(ctx context.Context, req idl.ListUsersRequest) (idl.ListUsersResponse, error) {
	var resp idl.ListUsersResponse
	path, err := buildGETPath("/listusers", req)
	if err != nil {
		return resp, fmt.Errorf("encode GET query: %w", err)
	}
	err = c.do(ctx, "GET", path, nil, &resp)
	return resp, err
}

func (c *httpClient) DeleteUser(ctx context.Context, req idl.DeleteUserRequest) (idl.DeleteUserResponse, error) {
	var resp idl.DeleteUserResponse
	path, err := buildRequestPath("/deleteuser", req)
	if err != nil {
		return resp, fmt.Errorf("encode request path: %w", err)
	}
	err = c.do(ctx, "DELETE", path, req, &resp)
	return resp, err
}

func (c *httpClient) UpdateUser(ctx context.Context, req idl.UpdateUserRequest) (idl.UpdateUserResponse, error) {
	var resp idl.UpdateUserResponse
	path, err := buildRequestPath("/updateuser", req)
	if err != nil {
		return resp, fmt.Errorf("encode request path: %w", err)
	}
	err = c.do(ctx, "PUT", path, req, &resp)
	return resp, err
}

func (c *httpClient) FindByEmail(ctx context.Context, req idl.GetUserRequest) (idl.GetUserResponse, error) {
	var resp idl.GetUserResponse
	path, err := buildGETPath("/findbyemail", req)
	if err != nil {
		return resp, fmt.Errorf("encode GET query: %w", err)
	}
	err = c.do(ctx, "GET", path, nil, &resp)
	return resp, err
}

func (c *httpClient) SearchUsers(ctx context.Context, req idl.ListUsersRequest) (idl.ListUsersResponse, error) {
	var resp idl.ListUsersResponse
	path, err := buildGETPath("/searchusers", req)
	if err != nil {
		return resp, fmt.Errorf("encode GET query: %w", err)
	}
	err = c.do(ctx, "GET", path, nil, &resp)
	return resp, err
}

func (c *httpClient) QueryStats(ctx context.Context, req idl.GetUserRequest) (idl.GetUserResponse, error) {
	var resp idl.GetUserResponse
	path, err := buildGETPath("/querystats", req)
	if err != nil {
		return resp, fmt.Errorf("encode GET query: %w", err)
	}
	err = c.do(ctx, "GET", path, nil, &resp)
	return resp, err
}

func (c *httpClient) RemoveExpired(ctx context.Context, req idl.DeleteUserRequest) (idl.DeleteUserResponse, error) {
	var resp idl.DeleteUserResponse
	path, err := buildRequestPath("/removeexpired", req)
	if err != nil {
		return resp, fmt.Errorf("encode request path: %w", err)
	}
	err = c.do(ctx, "DELETE", path, req, &resp)
	return resp, err
}

func (c *httpClient) EditProfile(ctx context.Context, req idl.UpdateUserRequest) (idl.UpdateUserResponse, error) {
	var resp idl.UpdateUserResponse
	path, err := buildRequestPath("/editprofile", req)
	if err != nil {
		return resp, fmt.Errorf("encode request path: %w", err)
	}
	err = c.do(ctx, "PUT", path, req, &resp)
	return resp, err
}

func (c *httpClient) ModifyEmail(ctx context.Context, req idl.UpdateUserRequest) (idl.UpdateUserResponse, error) {
	var resp idl.UpdateUserResponse
	path, err := buildRequestPath("/modifyemail", req)
	if err != nil {
		return resp, fmt.Errorf("encode request path: %w", err)
	}
	err = c.do(ctx, "PUT", path, req, &resp)
	return resp, err
}

func (c *httpClient) PatchStatus(ctx context.Context, req idl.UpdateUserRequest) (idl.UpdateUserResponse, error) {
	var resp idl.UpdateUserResponse
	path, err := buildRequestPath("/patchstatus", req)
	if err != nil {
		return resp, fmt.Errorf("encode request path: %w", err)
	}
	err = c.do(ctx, "PUT", path, req, &resp)
	return resp, err
}

// ─────────────────────────── gRPC implementation ──────────────────────────────
