// Code generated by microgen. DO NOT EDIT.
package main

import (
	"github.com/gorilla/mux"
	"gorm.io/gorm"
	"example.com/gen_idl_extend_check_missing/model"
)

type generatedRouteEntry struct {
	Method  string
	Path    string
	Handler string
}

type generatedRuntime struct {
	routeEntries []generatedRouteEntry
	httpRegistrars []func(*mux.Router)
}

func (rt generatedRuntime) registerRoutes(r *mux.Router) {
	for _, register := range rt.httpRegistrars {
		register(r)
	}
}
func (rt generatedRuntime) autoMigrate(db *gorm.DB) error {
	if db == nil {
		return nil
	}
	return db.AutoMigrate(
		&model.User{},
	)
}

func generatedRouteEntries(rt generatedRuntime, customRoutes []generatedRouteEntry, withSwag bool, withSkill bool) []generatedRouteEntry {
	routes := []generatedRouteEntry{
		{Method: "GET", Path: "/health", Handler: "health"},
		{Method: "GET", Path: "/debug/routes", Handler: "debug"},
	}
	routes = append(routes, rt.routeEntries...)
	routes = append(routes, customRoutes...)
	if withSwag {
		routes = append(routes, generatedRouteEntry{Method: "GET", Path: "/swagger/", Handler: "swagger-ui"})
	}
	if withSkill {
		routes = append(routes, generatedRouteEntry{Method: "GET", Path: "/skill", Handler: "skill"})
	}
	return routes
}
