/* Code generated by microgen. DO NOT EDIT. */

export type FetchLike = (input: string | URL, init?: RequestInit) => Promise<Response>;

export interface ClientOptions {
  fetch?: FetchLike;
  headers?: Record<string, string>;
}

export interface RequestOptions {
  signal?: AbortSignal;
  headers?: Record<string, string>;
}

export class APIError extends Error {
  constructor(
    public readonly status: number,
    public readonly body: string,
  ) {
    super(`API request failed with status ${status}: ${body}`);
    this.name = "APIError";
  }
}

function encodePathValue(name: string, value: unknown, duration: boolean): string {
  if (value === undefined || value === null || value === "") {
    throw new Error(`missing path parameter: ${name}`);
  }
  return encodeURIComponent(queryScalar(value, duration));
}

function queryScalar(value: unknown, duration: boolean): string {
  if (duration && typeof value === "number") {
    return `${value}ns`;
  }
  if (value instanceof Date) {
    return value.toISOString();
  }
  return String(value);
}

function appendQueryValue(
  query: URLSearchParams,
  name: string,
  value: unknown,
  duration: boolean,
): void {
  if (value === undefined || value === null) {
    return;
  }
  const values = Array.isArray(value) ? value : [value];
  for (const item of values) {
    query.append(name, queryScalar(item, duration));
  }
}

class BaseClient {
  private readonly baseURL: string;
  private readonly fetcher: FetchLike;
  private readonly headers: Record<string, string>;

  constructor(baseURL: string, options: ClientOptions = {}) {
    const fetcher = options.fetch ?? globalThis.fetch;
    if (typeof fetcher !== "function") {
      throw new Error("a Fetch API implementation is required");
    }
    this.baseURL = baseURL.replace(/\/+$/, "");
    this.fetcher = fetcher;
    this.headers = { ...options.headers };
  }

  protected async request<T>(
    method: string,
    path: string,
    body: unknown,
    options: RequestOptions,
  ): Promise<T> {
    const headers: Record<string, string> = {
      Accept: "application/json",
      ...this.headers,
      ...options.headers,
    };
    if (body !== undefined) {
      headers["Content-Type"] = "application/json; charset=utf-8";
    }
    const response = await this.fetcher(this.baseURL + path, {
      method,
      headers,
      body: body === undefined ? undefined : JSON.stringify(body),
      signal: options.signal,
    });
    const text = await response.text();
    if (!response.ok) {
      throw new APIError(response.status, text);
    }
    if (text === "" || response.status === 204) {
      return undefined as T;
    }
    return JSON.parse(text) as T;
  }
}

export interface CreateUserRequest {
  "name": string;
  "email": string;
}

export interface CreateUserResponse {
  "id": string;
}

export interface GetUserRequest {
  "id": string;
}

export interface GetUserResponse {
  "id": string;
  "name": string;
  "email": string;
}

/** UserService handles user operations. */
export class UserServiceClient extends BaseClient {
  /** GetUser retrieves a user by ID. */
  async getUser(request: GetUserRequest, options: RequestOptions = {}): Promise<GetUserResponse> {
    let path = "/api/proto/userservice/getuser";
    const query = new URLSearchParams();
    appendQueryValue(query, "id", request["id"], false);
    const encodedQuery = query.toString();
    if (encodedQuery !== "") {
      path += (path.includes("?") ? "&" : "?") + encodedQuery;
    }
    return this.request<GetUserResponse>("GET", path, undefined, options);
  }

  /** CreateUser creates a new user. */
  async createUser(request: CreateUserRequest, options: RequestOptions = {}): Promise<CreateUserResponse> {
    let path = "/api/proto/userservice/createuser";
    return this.request<CreateUserResponse>("POST", path, request, options);
  }

}

export class APIClient {
  public readonly userService: UserServiceClient;

  constructor(baseURL: string, options: ClientOptions = {}) {
    this.userService = new UserServiceClient(baseURL, options);
  }
}
