// Code generated by microgen. DO NOT EDIT.
package main

import (
	kitlog "github.com/dreamsxin/go-kit/log"
	userserviceEndpoint "example.com/gen_idl_custom_routes/endpoint/userservice"
	userserviceSvc "example.com/gen_idl_custom_routes/service/userservice"
)

type generatedServices struct {
	userserviceSvc       userserviceSvc.UserService
	userserviceEndpoints userserviceEndpoint.UserServiceEndpoints
}

func initGeneratedServices(logger *kitlog.Logger) generatedServices {
	generated := generatedServices{}

	_ = logger
	generated.userserviceSvc = userserviceSvc.NewService(nil)
	generated.userserviceEndpoints = userserviceEndpoint.MakeServerEndpoints(generated.userserviceSvc, logger)

	return generated
}
