// Code generated by microgen. DO NOT EDIT.
package main

import (
	orderserviceEndpoint "example.com/gen_idl_extend_append/endpoint/orderservice"
	userserviceEndpoint "example.com/gen_idl_extend_append/endpoint/userservice"
	orderserviceSvc "example.com/gen_idl_extend_append/service/orderservice"
	userserviceSvc "example.com/gen_idl_extend_append/service/userservice"
	kitlog "github.com/dreamsxin/go-kit/v2/log"
)

type generatedServices struct {
	userserviceSvc        userserviceSvc.UserService
	userserviceEndpoints  userserviceEndpoint.UserServiceEndpoints
	orderserviceSvc       orderserviceSvc.OrderService
	orderserviceEndpoints orderserviceEndpoint.OrderServiceEndpoints
}

func initGeneratedServices(logger *kitlog.Logger) generatedServices {
	generated := generatedServices{}

	_ = logger
	generated.userserviceSvc = userserviceSvc.NewService(nil)
	generated.userserviceEndpoints = userserviceEndpoint.MakeServerEndpoints(generated.userserviceSvc, logger)
	generated.orderserviceSvc = orderserviceSvc.NewService(nil)
	generated.orderserviceEndpoints = orderserviceEndpoint.MakeServerEndpoints(generated.orderserviceSvc, logger)

	return generated
}
