package model

import (
	"time"

	"gorm.io/gorm"
)

// Code generated by microgen. DO NOT EDIT.

// Product
type Product struct {
	ID uint `json:"id" gorm:"primaryKey"`
	Name string `json:"name" gorm:"not null"`
	CreatedAt time.Time      `json:"created_at" gorm:"autoCreateTime"`
	UpdatedAt time.Time      `json:"updated_at" gorm:"autoUpdateTime"`
	DeletedAt gorm.DeletedAt `json:"deleted_at,omitempty" gorm:"index"`
}

// TableName specifies the gorm table name.
func (Product) TableName() string {
	return "product"
}
