// Code generated by microgen. DO NOT EDIT.
// Re-generate with: microgen -idl <idl.go> -out <outdir> ...
//
// config.go defines the generated config model and default values.
package config

import (
	"fmt"
	"strings"
	"time"
)

// Config groups all generated config sections.
type Config struct {
	Server     ServerConfig     `yaml:"server" mapstructure:"server"`
	Logging    LoggingConfig    `yaml:"logging" mapstructure:"logging"`
	Middleware MiddlewareConfig `yaml:"middleware" mapstructure:"middleware"`
	Debug      DebugConfig      `yaml:"debug" mapstructure:"debug"`
	Remote     RemoteConfig     `yaml:"remote" mapstructure:"remote"`
}

// ServerConfig holds HTTP and optional gRPC listener settings.
type ServerConfig struct {
	HTTPAddr                string        `yaml:"http_addr" mapstructure:"http_addr"`
	GRPCAddr                string        `yaml:"grpc_addr" mapstructure:"grpc_addr"`
	ReadTimeout             time.Duration `yaml:"read_timeout" mapstructure:"read_timeout"`
	WriteTimeout            time.Duration `yaml:"write_timeout" mapstructure:"write_timeout"`
	GracefulShutdownTimeout time.Duration `yaml:"graceful_shutdown_timeout" mapstructure:"graceful_shutdown_timeout"`
}

// LoggingConfig holds logger settings.
type LoggingConfig struct {
	Level  string `yaml:"level" mapstructure:"level"`
	Format string `yaml:"format" mapstructure:"format"`
}

// MiddlewareConfig groups generated middleware settings.
type MiddlewareConfig struct {
	CircuitBreaker CircuitBreakerConfig `yaml:"circuit_breaker" mapstructure:"circuit_breaker"`
	RateLimit      RateLimitConfig      `yaml:"rate_limit" mapstructure:"rate_limit"`
	Retry          RetryConfig          `yaml:"retry" mapstructure:"retry"`
}

// CircuitBreakerConfig holds circuit breaker settings.
type CircuitBreakerConfig struct {
	Enabled          bool          `yaml:"enabled" mapstructure:"enabled"`
	FailureThreshold int           `yaml:"failure_threshold" mapstructure:"failure_threshold"`
	Timeout          time.Duration `yaml:"timeout" mapstructure:"timeout"`
}

// RateLimitConfig holds rate limiting settings.
type RateLimitConfig struct {
	Enabled           bool    `yaml:"enabled" mapstructure:"enabled"`
	RequestsPerSecond float64 `yaml:"requests_per_second" mapstructure:"requests_per_second"`
}

// RetryConfig holds retry settings.
type RetryConfig struct {
	Enabled     bool          `yaml:"enabled" mapstructure:"enabled"`
	MaxAttempts int           `yaml:"max_attempts" mapstructure:"max_attempts"`
	Backoff     time.Duration `yaml:"backoff" mapstructure:"backoff"`
}

// DebugConfig holds debug endpoint settings.
type DebugConfig struct {
	RoutesEnabled bool `yaml:"routes_enabled" mapstructure:"routes_enabled"`
	PrintRoutes   bool `yaml:"print_routes" mapstructure:"print_routes"`
}

// RemoteConfig holds optional remote-config loading settings.
type RemoteConfig struct {
	Enabled         bool          `yaml:"enabled" mapstructure:"enabled"`
	Provider        string        `yaml:"provider" mapstructure:"provider"`
	Endpoint        string        `yaml:"endpoint" mapstructure:"endpoint"`
	Namespace       string        `yaml:"namespace" mapstructure:"namespace"`
	Group           string        `yaml:"group" mapstructure:"group"`
	DataID          string        `yaml:"data_id" mapstructure:"data_id"`
	Timeout         time.Duration `yaml:"timeout" mapstructure:"timeout"`
	FallbackToLocal bool          `yaml:"fallback_to_local" mapstructure:"fallback_to_local"`
}

// Default returns generated defaults aligned with config.yaml.
func Default() *Config {
	return &Config{
		Server: ServerConfig{
			HTTPAddr:                ":8080",
			GRPCAddr:                ":8081",
			ReadTimeout:             15 * time.Second,
			WriteTimeout:            15 * time.Second,
			GracefulShutdownTimeout: 30 * time.Second,
		},
		Logging: LoggingConfig{
			Level:  "info",
			Format: "json",
		},
		Middleware: MiddlewareConfig{
			CircuitBreaker: CircuitBreakerConfig{
				Enabled:          false,
				FailureThreshold: 5,
				Timeout:          60 * time.Second,
			},
			RateLimit: RateLimitConfig{
				Enabled:           true,
				RequestsPerSecond: 100,
			},
			Retry: RetryConfig{
				Enabled:     false,
				MaxAttempts: 3,
				Backoff:     2 * time.Second,
			},
		},
		Debug: DebugConfig{
			RoutesEnabled: true,
			PrintRoutes:   true,
		},
		Remote: RemoteConfig{
			Enabled:         false,
			Provider:        "",
			Endpoint:        "",
			Namespace:       "",
			Group:           "",
			DataID:          "",
			Timeout:         5 * time.Second,
			FallbackToLocal: true,
		},
	}
}

// Validate checks the final merged configuration before runtime wiring starts.
func (cfg *Config) Validate() error {
	if cfg == nil {
		return fmt.Errorf("config: nil config")
	}
	if strings.TrimSpace(cfg.Server.HTTPAddr) == "" {
		return fmt.Errorf("config: server.http_addr is required")
	}
	if strings.TrimSpace(cfg.Server.GRPCAddr) == "" {
		return fmt.Errorf("config: server.grpc_addr is required")
	}
	if cfg.Server.ReadTimeout < 0 {
		return fmt.Errorf("config: server.read_timeout cannot be negative")
	}
	if cfg.Server.WriteTimeout < 0 {
		return fmt.Errorf("config: server.write_timeout cannot be negative")
	}
	if cfg.Server.GracefulShutdownTimeout <= 0 {
		return fmt.Errorf("config: server.graceful_shutdown_timeout must be > 0")
	}

	switch strings.ToLower(strings.TrimSpace(cfg.Logging.Level)) {
	case "debug", "info", "warn", "error", "dpanic", "panic", "fatal":
	default:
		return fmt.Errorf("config: unsupported logging.level %q", cfg.Logging.Level)
	}
	switch strings.ToLower(strings.TrimSpace(cfg.Logging.Format)) {
	case "json", "console":
	default:
		return fmt.Errorf("config: unsupported logging.format %q", cfg.Logging.Format)
	}

	if cfg.Middleware.CircuitBreaker.Enabled {
		if cfg.Middleware.CircuitBreaker.FailureThreshold <= 0 {
			return fmt.Errorf("config: middleware.circuit_breaker.failure_threshold must be > 0")
		}
		if cfg.Middleware.CircuitBreaker.Timeout <= 0 {
			return fmt.Errorf("config: middleware.circuit_breaker.timeout must be > 0")
		}
	}
	if cfg.Middleware.RateLimit.Enabled && cfg.Middleware.RateLimit.RequestsPerSecond <= 0 {
		return fmt.Errorf("config: middleware.rate_limit.requests_per_second must be > 0")
	}
	if cfg.Middleware.Retry.Enabled {
		if cfg.Middleware.Retry.MaxAttempts < 2 {
			return fmt.Errorf("config: middleware.retry.max_attempts must be >= 2")
		}
		if cfg.Middleware.Retry.Backoff < 0 {
			return fmt.Errorf("config: middleware.retry.backoff cannot be negative")
		}
	}

	if cfg.Remote.Enabled {
		provider := strings.ToLower(strings.TrimSpace(cfg.Remote.Provider))
		if provider != "consul" {
			return fmt.Errorf("config: unsupported remote.provider %q", cfg.Remote.Provider)
		}
		if strings.TrimSpace(cfg.Remote.Endpoint) == "" {
			return fmt.Errorf("config: remote.endpoint is required")
		}
		if strings.TrimSpace(cfg.Remote.DataID) == "" {
			return fmt.Errorf("config: remote.data_id is required")
		}
		if cfg.Remote.Timeout <= 0 {
			return fmt.Errorf("config: remote.timeout must be > 0")
		}
	}
	return nil
}

const envPrefix = "APP_"
