// Code generated by microgen. DO NOT EDIT.
package config

// Load resolves defaults -> local YAML -> remote -> final env overrides, then
// validates the complete runtime configuration.
func Load(path string) (*Config, error) {
	cfg, err := LoadLocal(path)
	if err != nil {
		return nil, err
	}
	if err := ApplyEnv(cfg); err != nil {
		return nil, err
	}
	cfg, err = LoadRemote(cfg)
	if err != nil {
		return nil, err
	}
	if err := ApplyEnv(cfg); err != nil {
		return nil, err
	}
	if err := cfg.Validate(); err != nil {
		return nil, err
	}
	return cfg, nil
}
