package userservice

import (
	"time"

	"github.com/sony/gobreaker"
	"golang.org/x/time/rate"

	"github.com/dreamsxin/go-kit/endpoint"
	"github.com/dreamsxin/go-kit/endpoint/circuitbreaker"
	"github.com/dreamsxin/go-kit/endpoint/ratelimit"
	kitlog "github.com/dreamsxin/go-kit/log"
)

// Code generated by microgen. DO NOT EDIT.

func generatedMiddlewareChain(logger *kitlog.Logger, cfg MiddlewareConfig, name string) []endpoint.Middleware {
	var middlewares []endpoint.Middleware

	if logger != nil {
		middlewares = append(middlewares, endpoint.LoggingMiddleware(logger, name))
	}
	if cfg.Timeout > 0 {
		middlewares = append(middlewares, endpoint.TimeoutMiddleware(cfg.Timeout))
	}
	if cfg.CBEnabled {
		cb := gobreaker.NewCircuitBreaker(gobreaker.Settings{
			Name: "UserService",
			ReadyToTrip: func(c gobreaker.Counts) bool {
				return c.ConsecutiveFailures >= cfg.CBFailureThreshold
			},
			Timeout: cfg.CBTimeout,
		})
		middlewares = append(middlewares, circuitbreaker.Gobreaker(cb))
	}
	if cfg.RLEnabled && cfg.RLRps > 0 {
		lim := rate.NewLimiter(rate.Limit(cfg.RLRps), int(cfg.RLRps))
		middlewares = append(middlewares, ratelimit.NewErroringLimiter(lim))
	}
	return middlewares
}

func applyGeneratedMiddleware(ep endpoint.Endpoint, logger *kitlog.Logger, cfg MiddlewareConfig, name string) endpoint.Endpoint {
	b := endpoint.NewBuilder(ep)
	for _, mw := range generatedMiddlewareChain(logger, cfg, name) {
		b = b.Use(mw)
	}
	return b.Build()
}

var _ = time.Second
