package repository

import (
	"context"
	"errors"
	"fmt"

	"gorm.io/gorm"
	"example.com/gen_idl_extend_append_model/model"
)

// Code generated by microgen. DO NOT EDIT.

// ProductRepository provides generated persistence helpers for Product.
type ProductRepository struct {
	db *DB
}

// NewProductRepository creates a ProductRepository.
func NewProductRepository(db *DB) *ProductRepository {
	return &ProductRepository{db: db}
}

// Create inserts a new record.
func (r *ProductRepository) Create(ctx context.Context, m *model.Product) error {
	if err := r.db.WithContext(ctx).Create(m).Error; err != nil {
		return fmt.Errorf("product.Create: %w", err)
	}
	return nil
}

// GetByID loads one record by primary key.
func (r *ProductRepository) GetByID(ctx context.Context, id uint) (*model.Product, error) {
	var m model.Product
	err := r.db.WithContext(ctx).First(&m, id).Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, nil
		}
		return nil, fmt.Errorf("product.GetByID(%d): %w", id, err)
	}
	return &m, nil
}

// Update saves the full record.
func (r *ProductRepository) Update(ctx context.Context, m *model.Product) error {
	if err := r.db.WithContext(ctx).Save(m).Error; err != nil {
		return fmt.Errorf("product.Update: %w", err)
	}
	return nil
}

// Updates applies a partial update.
func (r *ProductRepository) Updates(ctx context.Context, id uint, values map[string]interface{}) error {
	result := r.db.WithContext(ctx).Model(&model.Product{}).Where("id = ?", id).Updates(values)
	if result.Error != nil {
		return fmt.Errorf("product.Updates(%d): %w", id, result.Error)
	}
	if result.RowsAffected == 0 {
		return fmt.Errorf("product.Updates(%d): %w", id, ErrNotFound)
	}
	return nil
}

// Delete removes one record.
func (r *ProductRepository) Delete(ctx context.Context, id uint) error {
	result := r.db.WithContext(ctx).Delete(&model.Product{}, id)
	if result.Error != nil {
		return fmt.Errorf("product.Delete(%d): %w", id, result.Error)
	}
	if result.RowsAffected == 0 {
		return fmt.Errorf("product.Delete(%d): %w", id, ErrNotFound)
	}
	return nil
}

// ProductListResult is the generated paged query result for Product.
type ProductListResult struct {
	Total    int64            `json:"total"`
	Page     int              `json:"page"`
	PageSize int              `json:"page_size"`
	Data     []model.Product `json:"data"`
}

// List performs a generated paged query.
func (r *ProductRepository) List(ctx context.Context, q PageQuery) (*ProductListResult, error) {
	q.normalize()

	db := r.db.WithContext(ctx).Model(&model.Product{})

	if q.Keyword != "" {
		kw := "%" + q.Keyword + "%"
		// TODO: Adjust the generated search conditions for your real fields.
		_ = kw
	}

	var total int64
	if err := db.Count(&total).Error; err != nil {
		return nil, fmt.Errorf("product.List count: %w", err)
	}

	order := q.OrderBy
	if q.Desc {
		order += " DESC"
	} else {
		order += " ASC"
	}
	db = db.Order(order)

	offset := (q.Page - 1) * q.PageSize
	db = db.Offset(offset).Limit(q.PageSize)

	var records []model.Product
	if err := db.Find(&records).Error; err != nil {
		return nil, fmt.Errorf("product.List query: %w", err)
	}

	return &ProductListResult{
		Total:    total,
		Page:     q.Page,
		PageSize: q.PageSize,
		Data:     records,
	}, nil
}
