// Code generated by microgen. DO NOT EDIT.
package config

import (
	"fmt"
	"strings"

	_ "github.com/spf13/viper/remote"
	"github.com/spf13/viper"
)

// LoadRemote optionally loads remote config on top of the local/env-resolved
// base config. The first concrete provider uses Viper remote support for
// Consul while preserving local fallback behavior.
func LoadRemote(cfg *Config) (*Config, error) {
	if cfg == nil {
		return nil, fmt.Errorf("config: nil config")
	}
	if !cfg.Remote.Enabled {
		return cfg, nil
	}

	provider := strings.ToLower(strings.TrimSpace(cfg.Remote.Provider))
	var loaded *Config
	var err error

	switch provider {
	case "consul":
		loaded, err = loadRemoteFromConsul(cfg)
	case "":
		err = fmt.Errorf("config: remote enabled but provider is empty")
	default:
		err = fmt.Errorf("config: unsupported remote provider %q", cfg.Remote.Provider)
	}

	if err != nil {
		if cfg.Remote.FallbackToLocal {
			return cfg, nil
		}
		return nil, err
	}

	return loaded, nil
}

func loadRemoteFromConsul(cfg *Config) (*Config, error) {
	endpoint := strings.TrimSpace(cfg.Remote.Endpoint)
	if endpoint == "" {
		return nil, fmt.Errorf("config: remote consul endpoint is empty")
	}

	dataID := strings.TrimSpace(cfg.Remote.DataID)
	if dataID == "" {
		return nil, fmt.Errorf("config: remote consul data_id is empty")
	}

	v := viper.New()
	v.SetConfigType("yaml")
	if err := v.AddRemoteProvider("consul", endpoint, dataID); err != nil {
		return nil, fmt.Errorf("config: add consul remote provider: %w", err)
	}
	if err := v.ReadRemoteConfig(); err != nil {
		return nil, fmt.Errorf("config: read consul remote config: %w", err)
	}

	merged := *cfg
	if err := v.Unmarshal(&merged); err != nil {
		return nil, fmt.Errorf("config: unmarshal consul remote config: %w", err)
	}

	return &merged, nil
}
