package repository

import (
	"context"
	"errors"

	"gorm.io/gorm"
)

// Code generated by microgen. DO NOT EDIT.

// PageQuery defines generated pagination and ordering parameters.
type PageQuery struct {
	Page     int    `json:"page" form:"page"`
	PageSize int    `json:"page_size" form:"page_size"`
	OrderBy  string `json:"order_by" form:"order_by"`
	Desc     bool   `json:"desc" form:"desc"`
	Keyword  string `json:"keyword" form:"keyword"`
}

func (q *PageQuery) normalize() {
	if q.Page <= 0 {
		q.Page = 1
	}
	if q.PageSize <= 0 {
		q.PageSize = 20
	}
	if q.PageSize > 200 {
		q.PageSize = 200
	}
	if q.OrderBy == "" {
		q.OrderBy = "id"
	}
}

// DB wraps gorm.DB for generated repositories.
type DB struct {
	db *gorm.DB
}

// NewDB creates a generated repository DB wrapper.
func NewDB(db *gorm.DB) *DB {
	return &DB{db: db}
}

// WithContext returns a context-bound gorm DB.
func (d *DB) WithContext(ctx context.Context) *gorm.DB {
	return d.db.WithContext(ctx)
}

// AutoMigrate migrates generated model types.
func (d *DB) AutoMigrate(dst ...interface{}) error {
	return d.db.AutoMigrate(dst...)
}

// ErrNotFound is returned when a generated repository cannot find a record.
var ErrNotFound = errors.New("record not found")
