/* Code generated by microgen. DO NOT EDIT. */

export type FetchLike = (input: string | URL, init?: RequestInit) => Promise<Response>;

export interface ClientOptions {
  fetch?: FetchLike;
  headers?: Record<string, string>;
}

export interface RequestOptions {
  signal?: AbortSignal;
  headers?: Record<string, string>;
}

export class APIError extends Error {
  constructor(
    public readonly status: number,
    public readonly body: string,
  ) {
    super(`API request failed with status ${status}: ${body}`);
    this.name = "APIError";
  }
}

function encodePathValue(name: string, value: unknown, duration: boolean): string {
  if (value === undefined || value === null || value === "") {
    throw new Error(`missing path parameter: ${name}`);
  }
  return encodeURIComponent(queryScalar(value, duration));
}

function queryScalar(value: unknown, duration: boolean): string {
  if (duration && typeof value === "number") {
    return `${value}ns`;
  }
  if (value instanceof Date) {
    return value.toISOString();
  }
  return String(value);
}

function appendQueryValue(
  query: URLSearchParams,
  name: string,
  value: unknown,
  duration: boolean,
): void {
  if (value === undefined || value === null) {
    return;
  }
  const values = Array.isArray(value) ? value : [value];
  for (const item of values) {
    query.append(name, queryScalar(item, duration));
  }
}

class BaseClient {
  private readonly baseURL: string;
  private readonly fetcher: FetchLike;
  private readonly headers: Record<string, string>;

  constructor(baseURL: string, options: ClientOptions = {}) {
    const fetcher = options.fetch ?? globalThis.fetch;
    if (typeof fetcher !== "function") {
      throw new Error("a Fetch API implementation is required");
    }
    this.baseURL = baseURL.replace(/\/+$/, "");
    this.fetcher = fetcher;
    this.headers = { ...options.headers };
  }

  protected async request<T>(
    method: string,
    path: string,
    body: unknown,
    options: RequestOptions,
  ): Promise<T> {
    const headers: Record<string, string> = {
      Accept: "application/json",
      ...this.headers,
      ...options.headers,
    };
    if (body !== undefined) {
      headers["Content-Type"] = "application/json; charset=utf-8";
    }
    const response = await this.fetcher(this.baseURL + path, {
      method,
      headers,
      body: body === undefined ? undefined : JSON.stringify(body),
      signal: options.signal,
    });
    const text = await response.text();
    if (!response.ok) {
      throw new APIError(response.status, text);
    }
    if (text === "" || response.status === 204) {
      return undefined as T;
    }
    return JSON.parse(text) as T;
  }
}

export interface CreateUserRequest {
  "username": string;
  "email": string;
}

export interface CreateUserResponse {
  "user"?: User;
  "error": string;
}

export interface DeleteUserRequest {
  "id": number;
}

export interface DeleteUserResponse {
  "success": boolean;
  "error": string;
}

export interface GetUserRequest {
  "id": number;
}

export interface GetUserResponse {
  "user"?: User;
  "error": string;
}

export interface ListUsersRequest {
  "page": number;
  "keyword": string;
}

export interface ListUsersResponse {
  "users": Array<User>;
  "total": number;
}

export interface UpdateUserRequest {
  "id": number;
  "username": string;
}

export interface UpdateUserResponse {
  "user"?: User;
  "error": string;
}

/** User is a simple DTO. */
export interface User {
  "id": number;
  "username": string;
  "email": string;
  "age": number;
  "score": number;
  "active": boolean;
}

/** UserService manages users. */
export class UserServiceClient extends BaseClient {
  /** CreateUser creates a new user. */
  async createUser(request: CreateUserRequest, options: RequestOptions = {}): Promise<CreateUserResponse> {
    let path = "/createuser";
    return this.request<CreateUserResponse>("POST", path, request, options);
  }

  /** GetUser retrieves a user by ID. */
  async getUser(request: GetUserRequest, options: RequestOptions = {}): Promise<GetUserResponse> {
    let path = "/getuser";
    const query = new URLSearchParams();
    appendQueryValue(query, "id", request["id"], false);
    const encodedQuery = query.toString();
    if (encodedQuery !== "") {
      path += (path.includes("?") ? "&" : "?") + encodedQuery;
    }
    return this.request<GetUserResponse>("GET", path, undefined, options);
  }

  /** ListUsers lists all users. */
  async listUsers(request: ListUsersRequest, options: RequestOptions = {}): Promise<ListUsersResponse> {
    let path = "/listusers";
    const query = new URLSearchParams();
    appendQueryValue(query, "page", request["page"], false);
    appendQueryValue(query, "keyword", request["keyword"], false);
    const encodedQuery = query.toString();
    if (encodedQuery !== "") {
      path += (path.includes("?") ? "&" : "?") + encodedQuery;
    }
    return this.request<ListUsersResponse>("GET", path, undefined, options);
  }

  /** DeleteUser removes a user. */
  async deleteUser(request: DeleteUserRequest, options: RequestOptions = {}): Promise<DeleteUserResponse> {
    let path = "/deleteuser";
    return this.request<DeleteUserResponse>("DELETE", path, request, options);
  }

  /** UpdateUser modifies a user. */
  async updateUser(request: UpdateUserRequest, options: RequestOptions = {}): Promise<UpdateUserResponse> {
    let path = "/updateuser";
    return this.request<UpdateUserResponse>("PUT", path, request, options);
  }

  /** FindByEmail finds users by email prefix. */
  async findByEmail(request: GetUserRequest, options: RequestOptions = {}): Promise<GetUserResponse> {
    let path = "/findbyemail";
    const query = new URLSearchParams();
    appendQueryValue(query, "id", request["id"], false);
    const encodedQuery = query.toString();
    if (encodedQuery !== "") {
      path += (path.includes("?") ? "&" : "?") + encodedQuery;
    }
    return this.request<GetUserResponse>("GET", path, undefined, options);
  }

  /** SearchUsers searches users. */
  async searchUsers(request: ListUsersRequest, options: RequestOptions = {}): Promise<ListUsersResponse> {
    let path = "/searchusers";
    const query = new URLSearchParams();
    appendQueryValue(query, "page", request["page"], false);
    appendQueryValue(query, "keyword", request["keyword"], false);
    const encodedQuery = query.toString();
    if (encodedQuery !== "") {
      path += (path.includes("?") ? "&" : "?") + encodedQuery;
    }
    return this.request<ListUsersResponse>("GET", path, undefined, options);
  }

  /** QueryStats returns statistics. */
  async queryStats(request: GetUserRequest, options: RequestOptions = {}): Promise<GetUserResponse> {
    let path = "/querystats";
    const query = new URLSearchParams();
    appendQueryValue(query, "id", request["id"], false);
    const encodedQuery = query.toString();
    if (encodedQuery !== "") {
      path += (path.includes("?") ? "&" : "?") + encodedQuery;
    }
    return this.request<GetUserResponse>("GET", path, undefined, options);
  }

  /** RemoveExpired removes expired users. */
  async removeExpired(request: DeleteUserRequest, options: RequestOptions = {}): Promise<DeleteUserResponse> {
    let path = "/removeexpired";
    return this.request<DeleteUserResponse>("DELETE", path, request, options);
  }

  /** EditProfile edits profile. */
  async editProfile(request: UpdateUserRequest, options: RequestOptions = {}): Promise<UpdateUserResponse> {
    let path = "/editprofile";
    return this.request<UpdateUserResponse>("PUT", path, request, options);
  }

  /** ModifyEmail modifies email. */
  async modifyEmail(request: UpdateUserRequest, options: RequestOptions = {}): Promise<UpdateUserResponse> {
    let path = "/modifyemail";
    return this.request<UpdateUserResponse>("PUT", path, request, options);
  }

  /** PatchStatus patches status. */
  async patchStatus(request: UpdateUserRequest, options: RequestOptions = {}): Promise<UpdateUserResponse> {
    let path = "/patchstatus";
    return this.request<UpdateUserResponse>("PUT", path, request, options);
  }

}

export class APIClient {
  public readonly userService: UserServiceClient;

  constructor(baseURL: string, options: ClientOptions = {}) {
    this.userService = new UserServiceClient(baseURL, options);
  }
}
