// Code generated by microgen. DO NOT EDIT.
package main

import (
	kitlog "github.com/dreamsxin/go-kit/log"
	"time"
	"example.com/gen_idl_components/config"
	userserviceEndpoint "example.com/gen_idl_components/endpoint/userservice"
	userserviceSvc "example.com/gen_idl_components/service/userservice"
)

type generatedServices struct {
	userserviceSvc       userserviceSvc.UserService
	userserviceEndpoints userserviceEndpoint.UserServiceEndpoints
}

func initGeneratedServices(logger *kitlog.Logger, cfg *config.Config) generatedServices {
	generated := generatedServices{}

	_ = logger
	_ = cfg
	_ = time.Second
	generated.userserviceSvc = userserviceSvc.NewService(nil)
	generated.userserviceEndpoints = userserviceEndpoint.MakeServerEndpointsWithConfig(generated.userserviceSvc, logger, userserviceEndpoint.MiddlewareConfig{
		CBEnabled:          cfg.Middleware.CircuitBreaker.Enabled,
		CBFailureThreshold: uint32(cfg.Middleware.CircuitBreaker.FailureThreshold),
		CBTimeout:          cfg.Middleware.CircuitBreaker.Timeout,
		RLEnabled:          cfg.Middleware.RateLimit.Enabled,
		RLRps:              cfg.Middleware.RateLimit.RequestsPerSecond,
		Timeout:            30 * time.Second,
	})

	return generated
}
