// Code generated by microgen. DO NOT EDIT.
package main

import (
	"google.golang.org/grpc"
	"net/http"
)

type generatedRouteEntry struct {
	Method  string
	Path    string
	Handler string
}

type generatedRuntime struct {
	routeEntries   []generatedRouteEntry
	httpRegistrars []func(*http.ServeMux)
	grpcRegistrars []func(*grpc.Server)
}

func (rt generatedRuntime) registerRoutes(r *http.ServeMux) {
	for _, register := range rt.httpRegistrars {
		register(r)
	}
}
func (rt generatedRuntime) registerGRPCServices(server *grpc.Server) {
	for _, register := range rt.grpcRegistrars {
		register(server)
	}
}

func generatedRouteEntries(rt generatedRuntime, customRoutes []generatedRouteEntry, withOpenAPI, withDebug bool) []generatedRouteEntry {
	routes := []generatedRouteEntry{
		{Method: "GET", Path: "/health", Handler: "health"},
	}
	if withDebug {
		routes = append(routes, generatedRouteEntry{Method: "GET", Path: "/debug/routes", Handler: "debug"})
	}
	routes = append(routes, rt.routeEntries...)
	routes = append(routes, customRoutes...)
	if withOpenAPI {
		routes = append(routes,
			generatedRouteEntry{Method: "GET", Path: "/openapi.json", Handler: "openapi"},
			generatedRouteEntry{Method: "GET", Path: "/schema.json", Handler: "json-schema"},
			generatedRouteEntry{Method: "GET", Path: "/swagger/", Handler: "swagger-ui"},
		)
	}

	return routes
}
