// Code generated by microgen. DO NOT EDIT.
package main

import (
	userserviceTransport "example.com/gen_proto_component_flow/transport/userservice"
	"google.golang.org/grpc"
	"net/http"
)

func (g generatedServices) generatedRuntime() generatedRuntime {
	rt := generatedRuntime{
		routeEntries: []generatedRouteEntry{
			{Method: "GET", Path: "/getuser", Handler: "GetUser"},
			{Method: "POST", Path: "/createuser", Handler: "CreateUser"},
		},
		httpRegistrars: []func(*http.ServeMux){
			func(router *http.ServeMux) {
				userserviceTransport.RegisterHTTPRoutes(router, g.userserviceEndpoints, "")
			},
		},
	}
	rt.grpcRegistrars = []func(*grpc.Server){
		func(server *grpc.Server) {
			userserviceTransport.RegisterGRPCServer(server, g.userserviceSvc, g.userserviceEndpoints)
		},
	}
	return rt
}
