// Code generated by microgen. DO NOT EDIT.
// Re-generate with: microgen -idl <idl.go> -out <outdir> ...
//
// config.go defines the generated config model and default values.
package config

import "time"

// Config groups all generated config sections.
type Config struct {
	Server    ServerConfig     `yaml:"server" mapstructure:"server"`
	Logging   LoggingConfig    `yaml:"logging" mapstructure:"logging"`
	Middleware MiddlewareConfig `yaml:"middleware" mapstructure:"middleware"`
	Debug      DebugConfig      `yaml:"debug" mapstructure:"debug"`
	Remote     RemoteConfig     `yaml:"remote" mapstructure:"remote"`
}

// ServerConfig holds HTTP and optional gRPC listener settings.
type ServerConfig struct {
	HTTPAddr                string        `yaml:"http_addr" mapstructure:"http_addr"`
	ReadTimeout             time.Duration `yaml:"read_timeout" mapstructure:"read_timeout"`
	WriteTimeout            time.Duration `yaml:"write_timeout" mapstructure:"write_timeout"`
	GracefulShutdownTimeout time.Duration `yaml:"graceful_shutdown_timeout" mapstructure:"graceful_shutdown_timeout"`
	SwaggerHost             string        `yaml:"swagger_host" mapstructure:"swagger_host"`
}

// LoggingConfig holds logger settings.
type LoggingConfig struct {
	Level  string `yaml:"level" mapstructure:"level"`
	Format string `yaml:"format" mapstructure:"format"`
}

// MiddlewareConfig groups generated middleware settings.
type MiddlewareConfig struct {
	CircuitBreaker CircuitBreakerConfig `yaml:"circuit_breaker" mapstructure:"circuit_breaker"`
	RateLimit      RateLimitConfig      `yaml:"rate_limit" mapstructure:"rate_limit"`
	Retry          RetryConfig          `yaml:"retry" mapstructure:"retry"`
}

// CircuitBreakerConfig holds circuit breaker settings.
type CircuitBreakerConfig struct {
	Enabled          bool          `yaml:"enabled" mapstructure:"enabled"`
	FailureThreshold int           `yaml:"failure_threshold" mapstructure:"failure_threshold"`
	Timeout          time.Duration `yaml:"timeout" mapstructure:"timeout"`
}

// RateLimitConfig holds rate limiting settings.
type RateLimitConfig struct {
	Enabled           bool    `yaml:"enabled" mapstructure:"enabled"`
	RequestsPerSecond float64 `yaml:"requests_per_second" mapstructure:"requests_per_second"`
}

// RetryConfig holds retry settings.
type RetryConfig struct {
	Enabled     bool          `yaml:"enabled" mapstructure:"enabled"`
	MaxAttempts int           `yaml:"max_attempts" mapstructure:"max_attempts"`
	Backoff     time.Duration `yaml:"backoff" mapstructure:"backoff"`
}

// DebugConfig holds debug endpoint settings.
type DebugConfig struct {
	RoutesEnabled bool `yaml:"routes_enabled" mapstructure:"routes_enabled"`
	PrintRoutes   bool `yaml:"print_routes" mapstructure:"print_routes"`
}

// RemoteConfig holds optional remote-config loading settings.
type RemoteConfig struct {
	Enabled         bool          `yaml:"enabled" mapstructure:"enabled"`
	Provider        string        `yaml:"provider" mapstructure:"provider"`
	Endpoint        string        `yaml:"endpoint" mapstructure:"endpoint"`
	Namespace       string        `yaml:"namespace" mapstructure:"namespace"`
	Group           string        `yaml:"group" mapstructure:"group"`
	DataID          string        `yaml:"data_id" mapstructure:"data_id"`
	Timeout         time.Duration `yaml:"timeout" mapstructure:"timeout"`
	FallbackToLocal bool          `yaml:"fallback_to_local" mapstructure:"fallback_to_local"`
}

// Default returns generated defaults aligned with config.yaml.
func Default() *Config {
	return &Config{
		Server: ServerConfig{
			HTTPAddr:                ":8080",
			ReadTimeout:             15 * time.Second,
			WriteTimeout:            15 * time.Second,
			GracefulShutdownTimeout: 30 * time.Second,
		},
		Logging: LoggingConfig{
			Level:  "info",
			Format: "json",
		},
		Middleware: MiddlewareConfig{
			CircuitBreaker: CircuitBreakerConfig{
				Enabled:          false,
				FailureThreshold: 5,
				Timeout:          60 * time.Second,
			},
			RateLimit: RateLimitConfig{
				Enabled:           true,
				RequestsPerSecond: 100,
			},
			Retry: RetryConfig{
				Enabled:     false,
				MaxAttempts: 3,
				Backoff:     2 * time.Second,
			},
		},
		Debug: DebugConfig{
			RoutesEnabled: true,
			PrintRoutes:   true,
		},
		Remote: RemoteConfig{
			Enabled:         false,
			Provider:        "",
			Endpoint:        "",
			Namespace:       "",
			Group:           "",
			DataID:          "",
			Timeout:         5 * time.Second,
			FallbackToLocal: true,
		},
	}
}

const envPrefix = "APP_"
