// Code generated by microgen. DO NOT EDIT.
package main

import (
	kitlog "github.com/dreamsxin/go-kit/log"
	"time"
	"example.com/gen_idl_default_flags/config"
	"example.com/gen_idl_default_flags/repository"
	userserviceEndpoint "example.com/gen_idl_default_flags/endpoint/userservice"
	userserviceSvc "example.com/gen_idl_default_flags/service/userservice"
)

type generatedServices struct {
	userserviceSvc       userserviceSvc.UserService
	userserviceEndpoints userserviceEndpoint.UserServiceEndpoints
}

func initGeneratedServices(logger *kitlog.Logger, cfg *config.Config, repoDB *repository.DB) generatedServices {
	generated := generatedServices{}

	_ = logger
	_ = cfg
	_ = time.Second
	_ = repoDB
	userRepo := repository.NewUserRepository(repoDB)
	_ = userRepo
	generated.userserviceSvc = userserviceSvc.NewServiceWithRepo(nil, userserviceSvc.GeneratedRepos{
		UserRepo: userRepo,
	})
	generated.userserviceEndpoints = userserviceEndpoint.MakeServerEndpointsWithConfig(generated.userserviceSvc, logger, userserviceEndpoint.MiddlewareConfig{
		CBEnabled:          cfg.Middleware.CircuitBreaker.Enabled,
		CBFailureThreshold: uint32(cfg.Middleware.CircuitBreaker.FailureThreshold),
		CBTimeout:          cfg.Middleware.CircuitBreaker.Timeout,
		RLEnabled:          cfg.Middleware.RateLimit.Enabled,
		RLRps:              cfg.Middleware.RateLimit.RequestsPerSecond,
		Timeout:            30 * time.Second,
	})

	return generated
}
