// Code generated by microgen. DO NOT EDIT.
// Re-generate with: microgen -idl <idl.go> -out <outdir> ...
//
// config.go defines the generated config model plus default, local-file,
// and environment-variable loading helpers.
package config

import (
	"fmt"
	"os"
	"strconv"
	"time"

	"gopkg.in/yaml.v3"
)

// Config groups all generated config sections.
type Config struct {
	Server    ServerConfig     `yaml:"server"`
	Logging   LoggingConfig    `yaml:"logging"`
	Database  DatabaseConfig   `yaml:"database"`
	Middleware MiddlewareConfig `yaml:"middleware"`
	Debug      DebugConfig      `yaml:"debug"`
	Remote     RemoteConfig     `yaml:"remote"`
}

// ServerConfig holds HTTP and optional gRPC listener settings.
type ServerConfig struct {
	HTTPAddr                string        `yaml:"http_addr"`
	ReadTimeout             time.Duration `yaml:"read_timeout"`
	WriteTimeout            time.Duration `yaml:"write_timeout"`
	GracefulShutdownTimeout time.Duration `yaml:"graceful_shutdown_timeout"`
}

// LoggingConfig holds logger settings.
type LoggingConfig struct {
	Level  string `yaml:"level"`
	Format string `yaml:"format"`
}

// DatabaseConfig holds database connection settings.
type DatabaseConfig struct {
	Driver          string        `yaml:"driver"`
	DSN             string        `yaml:"dsn"`
	MaxOpenConns    int           `yaml:"max_open_conns"`
	MaxIdleConns    int           `yaml:"max_idle_conns"`
	ConnMaxLifetime time.Duration `yaml:"conn_max_lifetime"`
}

// MiddlewareConfig groups generated middleware settings.
type MiddlewareConfig struct {
	CircuitBreaker CircuitBreakerConfig `yaml:"circuit_breaker"`
	RateLimit      RateLimitConfig      `yaml:"rate_limit"`
	Retry          RetryConfig          `yaml:"retry"`
}

// CircuitBreakerConfig holds circuit breaker settings.
type CircuitBreakerConfig struct {
	Enabled          bool          `yaml:"enabled"`
	FailureThreshold int           `yaml:"failure_threshold"`
	Timeout          time.Duration `yaml:"timeout"`
}

// RateLimitConfig holds rate limiting settings.
type RateLimitConfig struct {
	Enabled           bool    `yaml:"enabled"`
	RequestsPerSecond float64 `yaml:"requests_per_second"`
}

// RetryConfig holds retry settings.
type RetryConfig struct {
	Enabled     bool          `yaml:"enabled"`
	MaxAttempts int           `yaml:"max_attempts"`
	Backoff     time.Duration `yaml:"backoff"`
}

// DebugConfig holds debug endpoint settings.
type DebugConfig struct {
	RoutesEnabled bool `yaml:"routes_enabled"`
	PrintRoutes   bool `yaml:"print_routes"`
}

// RemoteConfig holds optional remote-config loading settings.
type RemoteConfig struct {
	Enabled         bool          `yaml:"enabled"`
	Provider        string        `yaml:"provider"`
	Endpoint        string        `yaml:"endpoint"`
	Namespace       string        `yaml:"namespace"`
	Group           string        `yaml:"group"`
	DataID          string        `yaml:"data_id"`
	Timeout         time.Duration `yaml:"timeout"`
	FallbackToLocal bool          `yaml:"fallback_to_local"`
}

// Default returns generated defaults aligned with config.yaml.
func Default() *Config {
	return &Config{
		Server: ServerConfig{
			HTTPAddr:                ":8080",
			ReadTimeout:             15 * time.Second,
			WriteTimeout:            15 * time.Second,
			GracefulShutdownTimeout: 30 * time.Second,
		},
		Logging: LoggingConfig{
			Level:  "info",
			Format: "json",
		},
		Database: DatabaseConfig{
			Driver:          "mysql",
			DSN:             "root:password@tcp(127.0.0.1:3306)/{svcname}?charset=utf8mb4&parseTime=True&loc=Local",
			MaxOpenConns:    20,
			MaxIdleConns:    5,
			ConnMaxLifetime: time.Hour,
		},
		Middleware: MiddlewareConfig{
			CircuitBreaker: CircuitBreakerConfig{
				Enabled:          true,
				FailureThreshold: 5,
				Timeout:          60 * time.Second,
			},
			RateLimit: RateLimitConfig{
				Enabled:           true,
				RequestsPerSecond: 100,
			},
			Retry: RetryConfig{
				Enabled:     true,
				MaxAttempts: 3,
				Backoff:     2 * time.Second,
			},
		},
		Debug: DebugConfig{
			RoutesEnabled: true,
			PrintRoutes:   true,
		},
		Remote: RemoteConfig{
			Enabled:         false,
			Provider:        "",
			Endpoint:        "",
			Namespace:       "",
			Group:           "",
			DataID:          "",
			Timeout:         5 * time.Second,
			FallbackToLocal: true,
		},
	}
}

const envPrefix = "APP_"

// LoadLocal loads config from a YAML file on top of the generated defaults.
// A missing file is treated as non-fatal so generated projects still run
// out of the box.
func LoadLocal(path string) (*Config, error) {
	cfg := Default()

	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return cfg, nil
		}
		return nil, fmt.Errorf("config: read %s: %w", path, err)
	}

	if err := yaml.Unmarshal(data, cfg); err != nil {
		return nil, fmt.Errorf("config: parse %s: %w", path, err)
	}

	return cfg, nil
}

// ApplyEnv applies scalar APP_* environment overrides to an existing config.
func ApplyEnv(cfg *Config) error {
	if cfg == nil {
		return fmt.Errorf("config: nil config")
	}

	readString := func(key string, target *string) {
		if value, ok := os.LookupEnv(envPrefix + key); ok {
			*target = value
		}
	}
	readBool := func(key string, target *bool) error {
		value, ok := os.LookupEnv(envPrefix + key)
		if !ok {
			return nil
		}
		parsed, err := strconv.ParseBool(value)
		if err != nil {
			return fmt.Errorf("config: parse %s%s as bool: %w", envPrefix, key, err)
		}
		*target = parsed
		return nil
	}
	readInt := func(key string, target *int) error {
		value, ok := os.LookupEnv(envPrefix + key)
		if !ok {
			return nil
		}
		parsed, err := strconv.Atoi(value)
		if err != nil {
			return fmt.Errorf("config: parse %s%s as int: %w", envPrefix, key, err)
		}
		*target = parsed
		return nil
	}
	readFloat64 := func(key string, target *float64) error {
		value, ok := os.LookupEnv(envPrefix + key)
		if !ok {
			return nil
		}
		parsed, err := strconv.ParseFloat(value, 64)
		if err != nil {
			return fmt.Errorf("config: parse %s%s as float64: %w", envPrefix, key, err)
		}
		*target = parsed
		return nil
	}
	readDuration := func(key string, target *time.Duration) error {
		value, ok := os.LookupEnv(envPrefix + key)
		if !ok {
			return nil
		}
		parsed, err := time.ParseDuration(value)
		if err != nil {
			return fmt.Errorf("config: parse %s%s as duration: %w", envPrefix, key, err)
		}
		*target = parsed
		return nil
	}

	readString("HTTP_ADDR", &cfg.Server.HTTPAddr)
	if err := readDuration("READ_TIMEOUT", &cfg.Server.ReadTimeout); err != nil {
		return err
	}
	if err := readDuration("WRITE_TIMEOUT", &cfg.Server.WriteTimeout); err != nil {
		return err
	}
	if err := readDuration("GRACEFUL_SHUTDOWN_TIMEOUT", &cfg.Server.GracefulShutdownTimeout); err != nil {
		return err
	}

	readString("LOG_LEVEL", &cfg.Logging.Level)
	readString("LOG_FORMAT", &cfg.Logging.Format)
	readString("DB_DRIVER", &cfg.Database.Driver)
	readString("DB_DSN", &cfg.Database.DSN)
	if err := readInt("DB_MAX_OPEN_CONNS", &cfg.Database.MaxOpenConns); err != nil {
		return err
	}
	if err := readInt("DB_MAX_IDLE_CONNS", &cfg.Database.MaxIdleConns); err != nil {
		return err
	}
	if err := readDuration("DB_CONN_MAX_LIFETIME", &cfg.Database.ConnMaxLifetime); err != nil {
		return err
	}

	if err := readBool("CB_ENABLED", &cfg.Middleware.CircuitBreaker.Enabled); err != nil {
		return err
	}
	if err := readInt("CB_FAILURE_THRESHOLD", &cfg.Middleware.CircuitBreaker.FailureThreshold); err != nil {
		return err
	}
	if err := readDuration("CB_TIMEOUT", &cfg.Middleware.CircuitBreaker.Timeout); err != nil {
		return err
	}

	if err := readBool("RATE_LIMIT_ENABLED", &cfg.Middleware.RateLimit.Enabled); err != nil {
		return err
	}
	if err := readFloat64("RATE_LIMIT_RPS", &cfg.Middleware.RateLimit.RequestsPerSecond); err != nil {
		return err
	}

	if err := readBool("RETRY_ENABLED", &cfg.Middleware.Retry.Enabled); err != nil {
		return err
	}
	if err := readInt("RETRY_MAX_ATTEMPTS", &cfg.Middleware.Retry.MaxAttempts); err != nil {
		return err
	}
	if err := readDuration("RETRY_BACKOFF", &cfg.Middleware.Retry.Backoff); err != nil {
		return err
	}

	if err := readBool("DEBUG_ROUTES_ENABLED", &cfg.Debug.RoutesEnabled); err != nil {
		return err
	}
	if err := readBool("DEBUG_PRINT_ROUTES", &cfg.Debug.PrintRoutes); err != nil {
		return err
	}
	if err := readBool("REMOTE_ENABLED", &cfg.Remote.Enabled); err != nil {
		return err
	}
	readString("REMOTE_PROVIDER", &cfg.Remote.Provider)
	readString("REMOTE_ENDPOINT", &cfg.Remote.Endpoint)
	readString("REMOTE_NAMESPACE", &cfg.Remote.Namespace)
	readString("REMOTE_GROUP", &cfg.Remote.Group)
	readString("REMOTE_DATA_ID", &cfg.Remote.DataID)
	if err := readDuration("REMOTE_TIMEOUT", &cfg.Remote.Timeout); err != nil {
		return err
	}
	if err := readBool("REMOTE_FALLBACK_TO_LOCAL", &cfg.Remote.FallbackToLocal); err != nil {
		return err
	}

	return nil
}

// LoadRemote is the generated seam for future remote-provider integration.
// The first milestone keeps it as a no-op so generated projects remain fully
// runnable with local config only.
func LoadRemote(cfg *Config) (*Config, error) {
	if cfg == nil {
		return nil, fmt.Errorf("config: nil config")
	}
	return cfg, nil
}

// Load preserves the generated public contract:
// defaults -> local YAML -> env overrides -> remote seam.
func Load(path string) (*Config, error) {
	cfg, err := LoadLocal(path)
	if err != nil {
		return nil, err
	}
	if err := ApplyEnv(cfg); err != nil {
		return nil, err
	}
	return LoadRemote(cfg)
}
