// Code generated by microgen. DO NOT EDIT.
package config

import (
	"fmt"
	"os"
	"strconv"
	"time"
)

// ApplyEnv applies scalar APP_* environment overrides to an existing config.
func ApplyEnv(cfg *Config) error {
	if cfg == nil {
		return fmt.Errorf("config: nil config")
	}

	readString := func(key string, target *string) {
		if value, ok := os.LookupEnv(envPrefix + key); ok {
			*target = value
		}
	}
	readBool := func(key string, target *bool) error {
		value, ok := os.LookupEnv(envPrefix + key)
		if !ok {
			return nil
		}
		parsed, err := strconv.ParseBool(value)
		if err != nil {
			return fmt.Errorf("config: parse %s%s as bool: %w", envPrefix, key, err)
		}
		*target = parsed
		return nil
	}
	readInt := func(key string, target *int) error {
		value, ok := os.LookupEnv(envPrefix + key)
		if !ok {
			return nil
		}
		parsed, err := strconv.Atoi(value)
		if err != nil {
			return fmt.Errorf("config: parse %s%s as int: %w", envPrefix, key, err)
		}
		*target = parsed
		return nil
	}
	readFloat64 := func(key string, target *float64) error {
		value, ok := os.LookupEnv(envPrefix + key)
		if !ok {
			return nil
		}
		parsed, err := strconv.ParseFloat(value, 64)
		if err != nil {
			return fmt.Errorf("config: parse %s%s as float64: %w", envPrefix, key, err)
		}
		*target = parsed
		return nil
	}
	readDuration := func(key string, target *time.Duration) error {
		value, ok := os.LookupEnv(envPrefix + key)
		if !ok {
			return nil
		}
		parsed, err := time.ParseDuration(value)
		if err != nil {
			return fmt.Errorf("config: parse %s%s as duration: %w", envPrefix, key, err)
		}
		*target = parsed
		return nil
	}

	readString("HTTP_ADDR", &cfg.Server.HTTPAddr)
	if err := readDuration("READ_TIMEOUT", &cfg.Server.ReadTimeout); err != nil {
		return err
	}
	if err := readDuration("WRITE_TIMEOUT", &cfg.Server.WriteTimeout); err != nil {
		return err
	}
	if err := readDuration("GRACEFUL_SHUTDOWN_TIMEOUT", &cfg.Server.GracefulShutdownTimeout); err != nil {
		return err
	}

	readString("LOG_LEVEL", &cfg.Logging.Level)
	readString("LOG_FORMAT", &cfg.Logging.Format)
	readString("DB_DRIVER", &cfg.Database.Driver)
	readString("DB_DSN", &cfg.Database.DSN)
	if err := readInt("DB_MAX_OPEN_CONNS", &cfg.Database.MaxOpenConns); err != nil {
		return err
	}
	if err := readInt("DB_MAX_IDLE_CONNS", &cfg.Database.MaxIdleConns); err != nil {
		return err
	}
	if err := readDuration("DB_CONN_MAX_LIFETIME", &cfg.Database.ConnMaxLifetime); err != nil {
		return err
	}

	if err := readBool("CB_ENABLED", &cfg.Middleware.CircuitBreaker.Enabled); err != nil {
		return err
	}
	if err := readInt("CB_FAILURE_THRESHOLD", &cfg.Middleware.CircuitBreaker.FailureThreshold); err != nil {
		return err
	}
	if err := readDuration("CB_TIMEOUT", &cfg.Middleware.CircuitBreaker.Timeout); err != nil {
		return err
	}

	if err := readBool("RATE_LIMIT_ENABLED", &cfg.Middleware.RateLimit.Enabled); err != nil {
		return err
	}
	if err := readFloat64("RATE_LIMIT_RPS", &cfg.Middleware.RateLimit.RequestsPerSecond); err != nil {
		return err
	}

	if err := readBool("RETRY_ENABLED", &cfg.Middleware.Retry.Enabled); err != nil {
		return err
	}
	if err := readInt("RETRY_MAX_ATTEMPTS", &cfg.Middleware.Retry.MaxAttempts); err != nil {
		return err
	}
	if err := readDuration("RETRY_BACKOFF", &cfg.Middleware.Retry.Backoff); err != nil {
		return err
	}

	if err := readBool("DEBUG_ROUTES_ENABLED", &cfg.Debug.RoutesEnabled); err != nil {
		return err
	}
	if err := readBool("DEBUG_PRINT_ROUTES", &cfg.Debug.PrintRoutes); err != nil {
		return err
	}
	if err := readBool("REMOTE_ENABLED", &cfg.Remote.Enabled); err != nil {
		return err
	}
	readString("REMOTE_PROVIDER", &cfg.Remote.Provider)
	readString("REMOTE_ENDPOINT", &cfg.Remote.Endpoint)
	readString("REMOTE_NAMESPACE", &cfg.Remote.Namespace)
	readString("REMOTE_GROUP", &cfg.Remote.Group)
	readString("REMOTE_DATA_ID", &cfg.Remote.DataID)
	if err := readDuration("REMOTE_TIMEOUT", &cfg.Remote.Timeout); err != nil {
		return err
	}
	if err := readBool("REMOTE_FALLBACK_TO_LOCAL", &cfg.Remote.FallbackToLocal); err != nil {
		return err
	}

	return nil
}
