// Code generated by microgen. DO NOT EDIT.
package config

import (
	"fmt"
	"os"

	"gopkg.in/yaml.v3"
)

// LoadLocal loads config from a YAML file on top of the generated defaults.
// A missing file is treated as non-fatal so generated projects still run
// out of the box.
func LoadLocal(path string) (*Config, error) {
	cfg := Default()

	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return cfg, nil
		}
		return nil, fmt.Errorf("config: read %s: %w", path, err)
	}

	if err := yaml.Unmarshal(data, cfg); err != nil {
		return nil, fmt.Errorf("config: parse %s: %w", path, err)
	}

	return cfg, nil
}
