// Code generated by microgen. DO NOT EDIT.
package main

import (
	kitlog "github.com/dreamsxin/go-kit/log"
	catalogserviceEndpoint "example.com/gen_fromdb_sqlite/endpoint/catalogservice"
	catalogserviceSvc "example.com/gen_fromdb_sqlite/service/catalogservice"
)

type generatedServices struct {
	catalogserviceSvc       catalogserviceSvc.CatalogService
	catalogserviceEndpoints catalogserviceEndpoint.CatalogServiceEndpoints
}

func initGeneratedServices(logger *kitlog.Logger) generatedServices {
	generated := generatedServices{}

	_ = logger
	generated.catalogserviceSvc = catalogserviceSvc.NewService(nil)
	generated.catalogserviceEndpoints = catalogserviceEndpoint.MakeServerEndpoints(generated.catalogserviceSvc, logger)

	return generated
}
