package generator_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/dreamsxin/go-kit/cmd/microgen/generator"
)

func TestScanExistingProject_DetectsServicesOwnershipAndWarnings(t *testing.T) {
	outDir := newTmpDir(t)
	project := parseIDLProject(t, "basic.go")

	gen := mustNewGenerator(t, generator.Options{
		OutputDir:  outDir,
		ImportPath: "example.com/basic",
		DBDriver:   "sqlite",
		WithConfig: true,
		WithDocs:   false,
		WithSkill:  true,
	})
	if err := gen.GenerateIR(project); err != nil {
		t.Fatalf("GenerateIR: %v", err)
	}

	existing, err := generator.ScanExistingProject(outDir)
	if err != nil {
		t.Fatalf("ScanExistingProject: %v", err)
	}

	if existing.ModulePath != "example.com/basic" {
		t.Fatalf("ModulePath = %q, want %q", existing.ModulePath, "example.com/basic")
	}
	if len(existing.Services) != 1 {
		t.Fatalf("len(Services) = %d, want 1", len(existing.Services))
	}
	if existing.Services[0].Name != "UserService" {
		t.Fatalf("service name = %q, want %q", existing.Services[0].Name, "UserService")
	}

	serviceOwn := existing.Ownership["service/userservice/service.go"]
	if serviceOwn.Tier != generator.OwnershipUserProtected {
		t.Fatalf("service ownership tier = %q, want %q", serviceOwn.Tier, generator.OwnershipUserProtected)
	}
	sdkOwn := existing.Ownership["sdk/userservicesdk/client.go"]
	if sdkOwn.Tier != generator.OwnershipGeneratorRebuildable {
		t.Fatalf("sdk ownership tier = %q, want %q", sdkOwn.Tier, generator.OwnershipGeneratorRebuildable)
	}
	mainOwn := existing.Ownership["cmd/main.go"]
	if mainOwn.Tier != generator.OwnershipUserProtected {
		t.Fatalf("main ownership tier = %q, want %q", mainOwn.Tier, generator.OwnershipUserProtected)
	}
	if existing.AggregationPoints.GeneratedServices == "" || existing.AggregationPoints.GeneratedRoutes == "" || existing.AggregationPoints.GeneratedRuntime == "" {
		t.Fatalf("AggregationPoints = %+v, want generated cmd aggregation files", existing.AggregationPoints)
	}
}

func TestScanExistingProject_DetectsAggregationPoints(t *testing.T) {
	outDir := newTmpDir(t)
	project := parseIDLProject(t, "basic.go")

	gen := mustNewGenerator(t, generator.Options{
		OutputDir:  outDir,
		ImportPath: "example.com/basic",
		DBDriver:   "sqlite",
		WithDocs:   false,
		WithConfig: false,
	})
	if err := gen.GenerateIR(project); err != nil {
		t.Fatalf("GenerateIR: %v", err)
	}

	for _, rel := range []string{
		"cmd/generated_services.go",
		"cmd/generated_routes.go",
		"cmd/generated_runtime.go",
		"endpoint/generated_chain.go",
	} {
		path := filepath.Join(outDir, filepath.FromSlash(rel))
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatalf("MkdirAll(%q): %v", path, err)
		}
		if err := os.WriteFile(path, []byte("// Code generated by microgen. DO NOT EDIT.\n"), 0o644); err != nil {
			t.Fatalf("WriteFile(%q): %v", path, err)
		}
	}

	existing, err := generator.ScanExistingProject(outDir)
	if err != nil {
		t.Fatalf("ScanExistingProject: %v", err)
	}

	if existing.AggregationPoints.GeneratedServices == "" || existing.AggregationPoints.GeneratedRoutes == "" {
		t.Fatalf("AggregationPoints = %+v, want cmd aggregation files", existing.AggregationPoints)
	}
	own := existing.Ownership["cmd/generated_services.go"]
	if own.Tier != generator.OwnershipGeneratorAggregation {
		t.Fatalf("generated_services ownership tier = %q, want %q", own.Tier, generator.OwnershipGeneratorAggregation)
	}
}

func TestScanExistingProject_RejectsUnsupportedLayoutWithGuidance(t *testing.T) {
	outDir := newTmpDir(t)
	if err := os.MkdirAll(filepath.Join(outDir, "cmd"), 0o755); err != nil {
		t.Fatalf("MkdirAll(cmd): %v", err)
	}
	if err := os.WriteFile(filepath.Join(outDir, "go.mod"), []byte("module example.com/custom\n"), 0o644); err != nil {
		t.Fatalf("WriteFile(go.mod): %v", err)
	}

	_, err := generator.ScanExistingProject(outDir)
	if err == nil || !strings.Contains(err.Error(), "supports only generated microgen project layouts") {
		t.Fatalf("ScanExistingProject error = %v, want unsupported-layout guidance", err)
	}
}

func TestBuildAppendServicePlan_RejectsDuplicateService(t *testing.T) {
	outDir := newTmpDir(t)
	project := parseIDLProject(t, "basic.go")

	gen := mustNewGenerator(t, generator.Options{
		OutputDir:  outDir,
		ImportPath: "example.com/basic",
		DBDriver:   "sqlite",
		WithDocs:   false,
		WithConfig: false,
	})
	if err := gen.GenerateIR(project); err != nil {
		t.Fatalf("GenerateIR: %v", err)
	}

	existing, err := generator.ScanExistingProject(outDir)
	if err != nil {
		t.Fatalf("ScanExistingProject: %v", err)
	}

	_, err = generator.BuildAppendServicePlan(existing, project, generator.Options{}, generator.ExtendOptions{
		AppendService: "UserService",
	})
	if err == nil || !strings.Contains(err.Error(), "already exists in the project") {
		t.Fatalf("BuildAppendServicePlan error = %v, want duplicate service error", err)
	}
}

func TestBuildAppendServicePlan_RequiresAggregationFiles(t *testing.T) {
	outDir := newTmpDir(t)
	base := parseIDLProject(t, "basic.go")
	source := parseIDLProject(t, "multi.go")

	gen := mustNewGenerator(t, generator.Options{
		OutputDir:  outDir,
		ImportPath: "example.com/basic",
		DBDriver:   "sqlite",
		WithDocs:   false,
		WithConfig: false,
	})
	if err := gen.GenerateIR(base); err != nil {
		t.Fatalf("GenerateIR: %v", err)
	}

	existing, err := generator.ScanExistingProject(outDir)
	if err != nil {
		t.Fatalf("ScanExistingProject: %v", err)
	}

	for _, path := range []string{
		existing.AggregationPoints.GeneratedServices,
		existing.AggregationPoints.GeneratedRoutes,
	} {
		if err := os.Remove(path); err != nil {
			t.Fatalf("Remove(%q): %v", path, err)
		}
	}
	existing, err = generator.ScanExistingProject(outDir)
	if err != nil {
		t.Fatalf("ScanExistingProject after removal: %v", err)
	}

	_, err = generator.BuildAppendServicePlan(existing, source, generator.Options{}, generator.ExtendOptions{
		AppendService: "OrderService",
	})
	if err == nil ||
		!strings.Contains(err.Error(), "generator-owned compatibility seams") ||
		!strings.Contains(err.Error(), "cmd/generated_services.go") ||
		!strings.Contains(err.Error(), "cmd/generated_routes.go") {
		t.Fatalf("BuildAppendServicePlan error = %v, want aggregation-file guidance", err)
	}
}

func TestBuildAppendServicePlan_TargetNotFoundListsAvailableServices(t *testing.T) {
	outDir := newTmpDir(t)
	base := parseIDLProject(t, "basic.go")

	gen := mustNewGenerator(t, generator.Options{
		OutputDir:  outDir,
		ImportPath: "example.com/basic",
		DBDriver:   "sqlite",
		WithDocs:   false,
		WithConfig: false,
	})
	if err := gen.GenerateIR(base); err != nil {
		t.Fatalf("GenerateIR: %v", err)
	}

	existing, err := generator.ScanExistingProject(outDir)
	if err != nil {
		t.Fatalf("ScanExistingProject: %v", err)
	}

	_, err = generator.BuildAppendServicePlan(existing, base, generator.Options{}, generator.ExtendOptions{
		AppendService: "OrderService",
	})
	if err == nil || !strings.Contains(err.Error(), "available: UserService") {
		t.Fatalf("BuildAppendServicePlan error = %v, want available services hint", err)
	}
}

func TestApplyAppendService_RequiresFullCombinedContract(t *testing.T) {
	outDir := newTmpDir(t)
	base := parseIDLProject(t, "basic.go")

	gen := mustNewGenerator(t, generator.Options{
		OutputDir:  outDir,
		ImportPath: "example.com/basic",
		DBDriver:   "sqlite",
		WithDocs:   false,
		WithConfig: false,
	})
	if err := gen.GenerateIR(base); err != nil {
		t.Fatalf("GenerateIR: %v", err)
	}

	partialContract := `package combined

import "context"

type PlaceOrderRequest struct{}
type PlaceOrderResponse struct{}

type OrderService interface {
	PlaceOrder(ctx context.Context, req PlaceOrderRequest) (PlaceOrderResponse, error)
}
`
	idlPath := filepath.Join(t.TempDir(), "partial.go")
	if err := os.WriteFile(idlPath, []byte(partialContract), 0o644); err != nil {
		t.Fatalf("WriteFile(%q): %v", idlPath, err)
	}
	source := parseIDLContentProject(t, partialContract)

	_, err := generator.ApplyAppendService(testTemplateFS, outDir, source, generator.ExtendOptions{
		AppendService: "OrderService",
	}, idlPath)
	if err == nil || !strings.Contains(err.Error(), "full combined Go IDL contract") || !strings.Contains(err.Error(), "UserService") {
		t.Fatalf("ApplyAppendService error = %v, want missing existing service guidance", err)
	}
}

func TestApplyAppendService_RejectsProtoInput(t *testing.T) {
	outDir := newTmpDir(t)
	base := parseIDLProject(t, "basic.go")

	gen := mustNewGenerator(t, generator.Options{
		OutputDir:  outDir,
		ImportPath: "example.com/basic",
		DBDriver:   "sqlite",
		WithDocs:   false,
		WithConfig: false,
	})
	if err := gen.GenerateIR(base); err != nil {
		t.Fatalf("GenerateIR: %v", err)
	}

	_, err := generator.ApplyAppendService(testTemplateFS, outDir, base, generator.ExtendOptions{
		AppendService: "OrderService",
	}, "combined.proto")
	if err == nil || !strings.Contains(err.Error(), ".proto input is not supported") {
		t.Fatalf("ApplyAppendService error = %v, want proto guidance", err)
	}
}

func TestBuildAppendServicePlan_ProducesDeterministicPlan(t *testing.T) {
	outDir := newTmpDir(t)
	base := parseIDLProject(t, "basic.go")
	source := parseIDLProject(t, "multi.go")

	gen := mustNewGenerator(t, generator.Options{
		OutputDir:  outDir,
		ImportPath: "example.com/basic",
		DBDriver:   "sqlite",
		WithDocs:   false,
		WithConfig: false,
	})
	if err := gen.GenerateIR(base); err != nil {
		t.Fatalf("GenerateIR: %v", err)
	}

	for _, rel := range []string{
		"cmd/generated_services.go",
		"cmd/generated_routes.go",
		"cmd/generated_runtime.go",
	} {
		path := filepath.Join(outDir, filepath.FromSlash(rel))
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatalf("MkdirAll(%q): %v", path, err)
		}
		if err := os.WriteFile(path, []byte("// generated\n"), 0o644); err != nil {
			t.Fatalf("WriteFile(%q): %v", path, err)
		}
	}

	existing, err := generator.ScanExistingProject(outDir)
	if err != nil {
		t.Fatalf("ScanExistingProject: %v", err)
	}

	plan, err := generator.BuildAppendServicePlan(existing, source, generator.Options{
		WithGRPC:  true,
		WithTests: true,
		WithSkill: true,
	}, generator.ExtendOptions{
		AppendService: "OrderService",
	})
	if err != nil {
		t.Fatalf("BuildAppendServicePlan: %v", err)
	}

	newPaths := collectPlannedFilePaths(plan.NewFiles)
	for _, want := range []string{
		filepath.Join(outDir, "service", "orderservice", "service.go"),
		filepath.Join(outDir, "endpoint", "orderservice", "endpoints.go"),
		filepath.Join(outDir, "transport", "orderservice", "transport_http.go"),
		filepath.Join(outDir, "transport", "orderservice", "transport_grpc.go"),
		filepath.Join(outDir, "pb", "orderservice", "orderservice.proto"),
		filepath.Join(outDir, "client", "orderservice", "demo.go"),
		filepath.Join(outDir, "sdk", "orderservicesdk", "client.go"),
		filepath.Join(outDir, "test", "orderservice_test.go"),
	} {
		if !containsString(newPaths, want) {
			t.Fatalf("plan.NewFiles missing %q: %v", want, newPaths)
		}
	}

	updatePaths := collectPlannedUpdatePaths(plan.UpdatedFiles)
	for _, want := range []string{
		filepath.Join(outDir, "idl.go"),
		filepath.Join(outDir, "cmd", "generated_routes.go"),
		filepath.Join(outDir, "cmd", "generated_runtime.go"),
		filepath.Join(outDir, "cmd", "generated_services.go"),
		filepath.Join(outDir, "skill", "skill.go"),
	} {
		if !containsString(updatePaths, want) {
			t.Fatalf("plan.UpdatedFiles missing %q: %v", want, updatePaths)
		}
	}
}

func TestBuildAppendModelPlan_RejectsDuplicateModel(t *testing.T) {
	outDir := newTmpDir(t)
	project := parseIDLProject(t, "basic.go")

	gen := mustNewGenerator(t, generator.Options{
		OutputDir:  outDir,
		ImportPath: "example.com/basic",
		DBDriver:   "sqlite",
		WithDocs:   false,
		WithConfig: false,
		WithModel:  true,
	})
	if err := gen.GenerateIR(project); err != nil {
		t.Fatalf("GenerateIR: %v", err)
	}

	existing, err := generator.ScanExistingProject(outDir)
	if err != nil {
		t.Fatalf("ScanExistingProject: %v", err)
	}

	_, err = generator.BuildAppendModelPlan(existing, project, generator.Options{WithModel: true}, generator.ExtendOptions{
		AppendModel: "User",
	})
	if err == nil || !strings.Contains(err.Error(), "append-model target already exists") {
		t.Fatalf("BuildAppendModelPlan error = %v, want duplicate model error", err)
	}
}

func TestBuildAppendModelPlan_ProducesDeterministicPlan(t *testing.T) {
	outDir := newTmpDir(t)
	base := parseIDLProject(t, "basic.go")
	source := parseIDLContentProject(t, appendModelCombinedIDL)

	gen := mustNewGenerator(t, generator.Options{
		OutputDir:  outDir,
		ImportPath: "example.com/basic",
		DBDriver:   "sqlite",
		WithDocs:   false,
		WithConfig: false,
		WithModel:  true,
	})
	if err := gen.GenerateIR(base); err != nil {
		t.Fatalf("GenerateIR: %v", err)
	}

	existing, err := generator.ScanExistingProject(outDir)
	if err != nil {
		t.Fatalf("ScanExistingProject: %v", err)
	}

	plan, err := generator.BuildAppendModelPlan(existing, source, generator.Options{WithModel: true}, generator.ExtendOptions{
		AppendModel: "Product",
	})
	if err != nil {
		t.Fatalf("BuildAppendModelPlan: %v", err)
	}

	newPaths := collectPlannedFilePaths(plan.NewFiles)
	for _, want := range []string{
		filepath.Join(outDir, "model", "generated_product.go"),
		filepath.Join(outDir, "model", "product.go"),
		filepath.Join(outDir, "repository", "generated_product_repository.go"),
	} {
		if !containsString(newPaths, want) {
			t.Fatalf("plan.NewFiles missing %q: %v", want, newPaths)
		}
	}

	updatePaths := collectPlannedUpdatePaths(plan.UpdatedFiles)
	for _, want := range []string{
		filepath.Join(outDir, "idl.go"),
		filepath.Join(outDir, "service", "userservice", "generated_repos.go"),
	} {
		if !containsString(updatePaths, want) {
			t.Fatalf("plan.UpdatedFiles missing %q: %v", want, updatePaths)
		}
	}
}

func TestBuildAppendModelPlan_ReportsCompatibilitySeams(t *testing.T) {
	outDir := newTmpDir(t)
	base := parseIDLProject(t, "basic.go")
	source := parseIDLContentProject(t, appendModelCombinedIDL)

	gen := mustNewGenerator(t, generator.Options{
		OutputDir:  outDir,
		ImportPath: "example.com/basic",
		DBDriver:   "sqlite",
		WithDocs:   false,
		WithConfig: false,
		WithModel:  true,
	})
	if err := gen.GenerateIR(base); err != nil {
		t.Fatalf("GenerateIR: %v", err)
	}

	reposPath := filepath.Join(outDir, "service", "userservice", "generated_repos.go")
	if err := os.Remove(reposPath); err != nil {
		t.Fatalf("Remove(%q): %v", reposPath, err)
	}

	existing, err := generator.ScanExistingProject(outDir)
	if err != nil {
		t.Fatalf("ScanExistingProject: %v", err)
	}

	_, err = generator.BuildAppendModelPlan(existing, source, generator.Options{WithModel: true}, generator.ExtendOptions{
		AppendModel: "Product",
	})
	if err == nil ||
		!strings.Contains(err.Error(), "generator-owned compatibility seams") ||
		!strings.Contains(err.Error(), "service/userservice/generated_repos.go") ||
		!strings.Contains(err.Error(), "retry extend") {
		t.Fatalf("BuildAppendModelPlan error = %v, want compatibility seam guidance", err)
	}
}

func TestApplyAppendModel_RequiresFullCombinedContract(t *testing.T) {
	outDir := newTmpDir(t)
	base := parseIDLProject(t, "basic.go")

	gen := mustNewGenerator(t, generator.Options{
		OutputDir:  outDir,
		ImportPath: "example.com/basic",
		DBDriver:   "sqlite",
		WithDocs:   false,
		WithConfig: false,
		WithModel:  true,
	})
	if err := gen.GenerateIR(base); err != nil {
		t.Fatalf("GenerateIR: %v", err)
	}

	partialContract := `package combined

type Product struct {
	ID uint ` + "`json:\"id\" gorm:\"primaryKey\"`" + `
	Name string ` + "`json:\"name\" gorm:\"not null\"`" + `
}
`
	idlPath := filepath.Join(t.TempDir(), "partial.go")
	if err := os.WriteFile(idlPath, []byte(partialContract), 0o644); err != nil {
		t.Fatalf("WriteFile(%q): %v", idlPath, err)
	}
	source := parseIDLContentProject(t, partialContract)

	_, err := generator.ApplyAppendModel(testTemplateFS, outDir, source, generator.ExtendOptions{
		AppendModel: "Product",
	}, idlPath)
	if err == nil || !strings.Contains(err.Error(), "full combined Go IDL contract") {
		t.Fatalf("ApplyAppendModel error = %v, want missing existing contract guidance", err)
	}
}

func TestApplyAppendModel_WritesNewFilesAndPreservesExistingHooks(t *testing.T) {
	outDir := newTmpDir(t)
	base := parseIDLProject(t, "basic.go")

	gen := mustNewGenerator(t, generator.Options{
		OutputDir:  outDir,
		ImportPath: "example.com/basic",
		DBDriver:   "sqlite",
		WithDocs:   false,
		WithConfig: false,
		WithModel:  true,
	})
	if err := gen.GenerateIR(base); err != nil {
		t.Fatalf("GenerateIR: %v", err)
	}

	hooksPath := filepath.Join(outDir, "model", "user.go")
	customMarker := "// user model customization stays here"
	if err := os.WriteFile(hooksPath, []byte(readFile(t, hooksPath)+"\n"+customMarker+"\n"), 0o644); err != nil {
		t.Fatalf("WriteFile(%q): %v", hooksPath, err)
	}

	idlPath := filepath.Join(t.TempDir(), "combined.go")
	if err := os.WriteFile(idlPath, []byte(appendModelCombinedIDL), 0o644); err != nil {
		t.Fatalf("WriteFile(%q): %v", idlPath, err)
	}
	source := parseIDLContentProject(t, appendModelCombinedIDL)

	if _, err := generator.ApplyAppendModel(testTemplateFS, outDir, source, generator.ExtendOptions{
		AppendModel: "Product",
	}, idlPath); err != nil {
		t.Fatalf("ApplyAppendModel: %v", err)
	}

	mustExist(t, filepath.Join(outDir, "model", "generated_product.go"))
	mustExist(t, filepath.Join(outDir, "model", "product.go"))
	mustExist(t, filepath.Join(outDir, "repository", "generated_product_repository.go"))
	mustContain(t, filepath.Join(outDir, "service", "userservice", "generated_repos.go"), "ProductRepo *repository.ProductRepository")
	mustContain(t, filepath.Join(outDir, "idl.go"), "type Product struct")
	mustContain(t, hooksPath, customMarker)
}

func TestBuildAppendMiddlewarePlan_RejectsAlreadyPresentMiddleware(t *testing.T) {
	outDir := newTmpDir(t)
	project := parseIDLProject(t, "basic.go")

	gen := mustNewGenerator(t, generator.Options{
		OutputDir:            outDir,
		ImportPath:           "example.com/basic",
		DBDriver:             "sqlite",
		WithDocs:             false,
		WithConfig:           false,
		GeneratedMiddlewares: []string{"tracing"},
	})
	if err := gen.GenerateIR(project); err != nil {
		t.Fatalf("GenerateIR: %v", err)
	}

	existing, err := generator.ScanExistingProject(outDir)
	if err != nil {
		t.Fatalf("ScanExistingProject: %v", err)
	}

	_, err = generator.BuildAppendMiddlewarePlan(existing, project, generator.Options{
		GeneratedMiddlewares: []string{"tracing"},
	}, generator.ExtendOptions{
		AppendMiddleware: []string{"tracing"},
	})
	if err == nil || !strings.Contains(err.Error(), "append-middleware target already exists") {
		t.Fatalf("BuildAppendMiddlewarePlan error = %v, want duplicate middleware error", err)
	}
}

func TestApplyAppendMiddleware_WritesGeneratedChainAndPreservesCustomChain(t *testing.T) {
	outDir := newTmpDir(t)
	project := parseIDLProject(t, "basic.go")

	gen := mustNewGenerator(t, generator.Options{
		OutputDir:  outDir,
		ImportPath: "example.com/basic",
		DBDriver:   "sqlite",
		WithDocs:   false,
		WithConfig: false,
	})
	if err := gen.GenerateIR(project); err != nil {
		t.Fatalf("GenerateIR: %v", err)
	}

	customChainPath := filepath.Join(outDir, "endpoint", "userservice", "custom_chain.go")
	customMarker := "// custom middleware chain stays here"
	if err := os.WriteFile(customChainPath, []byte(readFile(t, customChainPath)+"\n"+customMarker+"\n"), 0o644); err != nil {
		t.Fatalf("WriteFile(%q): %v", customChainPath, err)
	}

	idlPath := filepath.Join("..", "parser", "testdata", "basic.go")
	if _, err := generator.ApplyAppendMiddleware(testTemplateFS, outDir, project, generator.ExtendOptions{
		AppendMiddleware: []string{"tracing", "error-handling", "metrics"},
	}, idlPath); err != nil {
		t.Fatalf("ApplyAppendMiddleware: %v", err)
	}

	generatedChainPath := filepath.Join(outDir, "endpoint", "userservice", "generated_chain.go")
	mustContain(t, generatedChainPath, "endpoint.TracingMiddleware()")
	mustContain(t, generatedChainPath, "endpoint.ErrorHandlingMiddleware(name)")
	mustContain(t, generatedChainPath, "endpoint.MetricsMiddleware(generatedMetrics(name))")
	mustContain(t, customChainPath, customMarker)
}

func TestBuildAppendMiddlewarePlan_ReportsCompatibilitySeams(t *testing.T) {
	outDir := newTmpDir(t)
	project := parseIDLProject(t, "basic.go")

	gen := mustNewGenerator(t, generator.Options{
		OutputDir:  outDir,
		ImportPath: "example.com/basic",
		DBDriver:   "sqlite",
		WithDocs:   false,
		WithConfig: false,
	})
	if err := gen.GenerateIR(project); err != nil {
		t.Fatalf("GenerateIR: %v", err)
	}

	generatedChainPath := filepath.Join(outDir, "endpoint", "userservice", "generated_chain.go")
	if err := os.Remove(generatedChainPath); err != nil {
		t.Fatalf("Remove(%q): %v", generatedChainPath, err)
	}

	existing, err := generator.ScanExistingProject(outDir)
	if err != nil {
		t.Fatalf("ScanExistingProject: %v", err)
	}

	_, err = generator.BuildAppendMiddlewarePlan(existing, project, generator.Options{}, generator.ExtendOptions{
		AppendMiddleware: []string{"tracing"},
	})
	if err == nil ||
		!strings.Contains(err.Error(), "generator-owned compatibility seams") ||
		!strings.Contains(err.Error(), "endpoint/userservice/generated_chain.go") ||
		!strings.Contains(err.Error(), "generated route and middleware seams") {
		t.Fatalf("BuildAppendMiddlewarePlan error = %v, want compatibility seam guidance", err)
	}
}

const appendModelCombinedIDL = `package combined

import "context"

type User struct {
	ID uint ` + "`json:\"id\" gorm:\"primaryKey\"`" + `
	Username string ` + "`json:\"username\" gorm:\"not null\"`" + `
}

type Product struct {
	ID uint ` + "`json:\"id\" gorm:\"primaryKey\"`" + `
	Name string ` + "`json:\"name\" gorm:\"not null\"`" + `
}

type CreateUserRequest struct {
	Username string ` + "`json:\"username\"`" + `
}

type CreateUserResponse struct {
	Error string ` + "`json:\"error\"`" + `
}

type GetUserRequest struct {
	ID uint ` + "`json:\"id\"`" + `
}

type GetUserResponse struct {
	User *User ` + "`json:\"user\"`" + `
	Error string ` + "`json:\"error\"`" + `
}

type UserService interface {
	CreateUser(ctx context.Context, req CreateUserRequest) (CreateUserResponse, error)
	GetUser(ctx context.Context, req GetUserRequest) (GetUserResponse, error)
}
`

func TestApplyAppendService_WritesNewFilesAndPreservesExistingService(t *testing.T) {
	outDir := newTmpDir(t)
	base := parseIDLProject(t, "basic.go")

	gen := mustNewGenerator(t, generator.Options{
		OutputDir:  outDir,
		ImportPath: "example.com/basic",
		DBDriver:   "sqlite",
		WithDocs:   false,
		WithConfig: false,
		WithSkill:  true,
	})
	if err := gen.GenerateIR(base); err != nil {
		t.Fatalf("GenerateIR: %v", err)
	}

	servicePath := filepath.Join(outDir, "service", "userservice", "service.go")
	customMarker := "// user customization stays here"
	if err := os.WriteFile(servicePath, []byte(readFile(t, servicePath)+"\n"+customMarker+"\n"), 0o644); err != nil {
		t.Fatalf("WriteFile(%q): %v", servicePath, err)
	}

	fullContract := `package combined

import "context"

type User struct {
	ID uint ` + "`json:\"id\" gorm:\"primaryKey\"`" + `
}

type CreateUserRequest struct {
	Username string ` + "`json:\"username\"`" + `
}
type CreateUserResponse struct {
	Error string ` + "`json:\"error\"`" + `
}
type GetUserRequest struct {
	ID uint ` + "`json:\"id\"`" + `
}
type GetUserResponse struct {
	User *User ` + "`json:\"user\"`" + `
	Error string ` + "`json:\"error\"`" + `
}

type UserService interface {
	CreateUser(ctx context.Context, req CreateUserRequest) (CreateUserResponse, error)
	GetUser(ctx context.Context, req GetUserRequest) (GetUserResponse, error)
}

type PlaceOrderRequest struct {
	UserID uint ` + "`json:\"user_id\"`" + `
}
type PlaceOrderResponse struct {
	OrderID uint ` + "`json:\"order_id\"`" + `
	Error string ` + "`json:\"error\"`" + `
}

type OrderService interface {
	PlaceOrder(ctx context.Context, req PlaceOrderRequest) (PlaceOrderResponse, error)
}
`
	idlPath := filepath.Join(t.TempDir(), "combined.go")
	if err := os.WriteFile(idlPath, []byte(fullContract), 0o644); err != nil {
		t.Fatalf("WriteFile(%q): %v", idlPath, err)
	}
	source := parseIDLContentProject(t, fullContract)

	if _, err := generator.ApplyAppendService(testTemplateFS, outDir, source, generator.ExtendOptions{
		AppendService: "OrderService",
	}, idlPath); err != nil {
		t.Fatalf("ApplyAppendService: %v", err)
	}

	mustExist(t, filepath.Join(outDir, "service", "orderservice", "service.go"))
	mustExist(t, filepath.Join(outDir, "endpoint", "orderservice", "endpoints.go"))
	mustExist(t, filepath.Join(outDir, "transport", "orderservice", "transport_http.go"))
	mustContain(t, filepath.Join(outDir, "cmd", "generated_routes.go"), "/placeorder")
	mustContain(t, filepath.Join(outDir, "cmd", "generated_services.go"), "orderserviceSvc")
	mustContain(t, filepath.Join(outDir, "skill", "skill.go"), "PlaceOrder")
	mustContain(t, filepath.Join(outDir, "idl.go"), "type OrderService interface")
	mustContain(t, servicePath, customMarker)
}

func collectPlannedFilePaths(files []generator.PlannedFile) []string {
	out := make([]string, 0, len(files))
	for _, file := range files {
		out = append(out, file.Path)
	}
	return out
}

func collectPlannedUpdatePaths(files []generator.PlannedUpdate) []string {
	out := make([]string, 0, len(files))
	for _, file := range files {
		out = append(out, file.Path)
	}
	return out
}

func containsString(items []string, want string) bool {
	for _, item := range items {
		if item == want {
			return true
		}
	}
	return false
}
