// Code generated by microgen. DO NOT EDIT.
//
// Package userservicesdk is the client SDK for UserService.
//
// Usage:
//
//	// HTTP
//	client := userservicesdk.New("http://localhost:8080")
//	resp, err := client.CreateUser(ctx, idl.CreateUserRequest{...})
//
// 
package userservicesdk

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"


	idl "example.com/gen_idl_extend_append"
)

// ─────────────────────────── Client interface ────────────────────────────────

// Client is the UserService client interface.
// It mirrors the server-side Service interface exactly, so any code that
// works against the interface can be tested with a mock.
type Client interface {
	// CreateUser - CreateUser creates a new user.
	CreateUser(ctx context.Context, req idl.CreateUserRequest) (idl.CreateUserResponse, error)
	// GetUser - GetUser retrieves a user by ID.
	GetUser(ctx context.Context, req idl.GetUserRequest) (idl.GetUserResponse, error)
	// ListUsers - ListUsers lists all users.
	ListUsers(ctx context.Context, req idl.ListUsersRequest) (idl.ListUsersResponse, error)
	// DeleteUser - DeleteUser removes a user.
	DeleteUser(ctx context.Context, req idl.DeleteUserRequest) (idl.DeleteUserResponse, error)
	// UpdateUser - UpdateUser modifies a user.
	UpdateUser(ctx context.Context, req idl.UpdateUserRequest) (idl.UpdateUserResponse, error)
	// FindByEmail - FindByEmail finds users by email prefix.
	FindByEmail(ctx context.Context, req idl.GetUserRequest) (idl.GetUserResponse, error)
	// SearchUsers - SearchUsers searches users.
	SearchUsers(ctx context.Context, req idl.ListUsersRequest) (idl.ListUsersResponse, error)
	// QueryStats - QueryStats returns statistics.
	QueryStats(ctx context.Context, req idl.GetUserRequest) (idl.GetUserResponse, error)
	// RemoveExpired - RemoveExpired removes expired users.
	RemoveExpired(ctx context.Context, req idl.DeleteUserRequest) (idl.DeleteUserResponse, error)
	// EditProfile - EditProfile edits profile.
	EditProfile(ctx context.Context, req idl.UpdateUserRequest) (idl.UpdateUserResponse, error)
	// ModifyEmail - ModifyEmail modifies email.
	ModifyEmail(ctx context.Context, req idl.UpdateUserRequest) (idl.UpdateUserResponse, error)
	// PatchStatus - PatchStatus patches status.
	PatchStatus(ctx context.Context, req idl.UpdateUserRequest) (idl.UpdateUserResponse, error)

}

// ─────────────────────────── HTTP Constructor ────────────────────────────────

// Option configures the HTTP client.
type Option func(*httpClient)

// WithTimeout sets the per-request HTTP timeout (default: 30s).
func WithTimeout(d time.Duration) Option {
	return func(c *httpClient) { c.timeout = d }
}

// WithHTTPClient replaces the default *http.Client.
func WithHTTPClient(hc *http.Client) Option {
	return func(c *httpClient) { c.http = hc }
}

// WithHeader adds a static header to every request (e.g. Authorization).
func WithHeader(key, value string) Option {
	return func(c *httpClient) { c.headers[key] = value }
}

// WithBearerToken is a shorthand for WithHeader("Authorization", "Bearer "+token).
func WithBearerToken(token string) Option {
	return WithHeader("Authorization", "Bearer "+token)
}

// WithRequestHook registers a function called before every request.
// Use it to inject dynamic headers (e.g. per-request auth tokens).
func WithRequestHook(fn func(r *http.Request)) Option {
	return func(c *httpClient) { c.hooks = append(c.hooks, fn) }
}

// New creates a UserService HTTP client.
//
// baseURL is the server base URL, e.g. "http://localhost:8080".
func New(baseURL string, opts ...Option) Client {
	c := &httpClient{
		baseURL: baseURL,
		timeout: 30 * time.Second,
		headers: make(map[string]string),
	}
	for _, o := range opts {
		o(c)
	}
	if c.http == nil {
		c.http = &http.Client{Timeout: c.timeout}
	}
	return c
}

// ─────────────────────────── gRPC Constructor ────────────────────────────────



// ─────────────────────────── HTTP implementation ──────────────────────────────

type httpClient struct {
	baseURL string
	timeout time.Duration
	http    *http.Client
	headers map[string]string
	hooks   []func(*http.Request)
}

// apiError is returned when the server responds with a non-2xx status.
type apiError struct {
	StatusCode int
	Body       string
}

func (e *apiError) Error() string {
	return fmt.Sprintf("userservicesdk: server returned %d: %s", e.StatusCode, e.Body)
}

func (c *httpClient) do(ctx context.Context, method, path string, reqBody, respBody interface{}) error {
	var bodyReader io.Reader
	if reqBody != nil {
		b, err := json.Marshal(reqBody)
		if err != nil {
			return fmt.Errorf("userservicesdk: marshal request: %w", err)
		}
		bodyReader = bytes.NewReader(b)
	}

	req, err := http.NewRequestWithContext(ctx, method, c.baseURL+path, bodyReader)
	if err != nil {
		return fmt.Errorf("userservicesdk: build request: %w", err)
	}
	if reqBody != nil {
		req.Header.Set("Content-Type", "application/json; charset=utf-8")
	}
	req.Header.Set("Accept", "application/json")
	for k, v := range c.headers {
		req.Header.Set(k, v)
	}
	for _, hook := range c.hooks {
		hook(req)
	}

	resp, err := c.http.Do(req)
	if err != nil {
		return fmt.Errorf("userservicesdk: send request: %w", err)
	}
	defer resp.Body.Close()

	raw, _ := io.ReadAll(resp.Body)
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return &apiError{StatusCode: resp.StatusCode, Body: string(raw)}
	}

	if respBody != nil {
		if err := json.Unmarshal(raw, respBody); err != nil {
			return fmt.Errorf("userservicesdk: decode response: %w", err)
		}
	}
	return nil
}


func (c *httpClient) CreateUser(ctx context.Context, req idl.CreateUserRequest) (idl.CreateUserResponse, error) {
	var resp idl.CreateUserResponse
	err := c.do(ctx, "POST", "/createuser", req, &resp)
	return resp, err
}

func (c *httpClient) GetUser(ctx context.Context, req idl.GetUserRequest) (idl.GetUserResponse, error) {
	var resp idl.GetUserResponse
	path := "/getuser"
	b, _ := json.Marshal(req)
	var params map[string]interface{}
	json.Unmarshal(b, &params) //nolint:errcheck
	if len(params) > 0 {
		query := "?"
		for k, v := range params {
			query += fmt.Sprintf("%s=%v&", k, v)
		}
		path += query[:len(query)-1]
	}
	err := c.do(ctx, "GET", path, nil, &resp)
	return resp, err
}

func (c *httpClient) ListUsers(ctx context.Context, req idl.ListUsersRequest) (idl.ListUsersResponse, error) {
	var resp idl.ListUsersResponse
	path := "/listusers"
	b, _ := json.Marshal(req)
	var params map[string]interface{}
	json.Unmarshal(b, &params) //nolint:errcheck
	if len(params) > 0 {
		query := "?"
		for k, v := range params {
			query += fmt.Sprintf("%s=%v&", k, v)
		}
		path += query[:len(query)-1]
	}
	err := c.do(ctx, "GET", path, nil, &resp)
	return resp, err
}

func (c *httpClient) DeleteUser(ctx context.Context, req idl.DeleteUserRequest) (idl.DeleteUserResponse, error) {
	var resp idl.DeleteUserResponse
	err := c.do(ctx, "DELETE", "/deleteuser", req, &resp)
	return resp, err
}

func (c *httpClient) UpdateUser(ctx context.Context, req idl.UpdateUserRequest) (idl.UpdateUserResponse, error) {
	var resp idl.UpdateUserResponse
	err := c.do(ctx, "PUT", "/updateuser", req, &resp)
	return resp, err
}

func (c *httpClient) FindByEmail(ctx context.Context, req idl.GetUserRequest) (idl.GetUserResponse, error) {
	var resp idl.GetUserResponse
	path := "/findbyemail"
	b, _ := json.Marshal(req)
	var params map[string]interface{}
	json.Unmarshal(b, &params) //nolint:errcheck
	if len(params) > 0 {
		query := "?"
		for k, v := range params {
			query += fmt.Sprintf("%s=%v&", k, v)
		}
		path += query[:len(query)-1]
	}
	err := c.do(ctx, "GET", path, nil, &resp)
	return resp, err
}

func (c *httpClient) SearchUsers(ctx context.Context, req idl.ListUsersRequest) (idl.ListUsersResponse, error) {
	var resp idl.ListUsersResponse
	path := "/searchusers"
	b, _ := json.Marshal(req)
	var params map[string]interface{}
	json.Unmarshal(b, &params) //nolint:errcheck
	if len(params) > 0 {
		query := "?"
		for k, v := range params {
			query += fmt.Sprintf("%s=%v&", k, v)
		}
		path += query[:len(query)-1]
	}
	err := c.do(ctx, "GET", path, nil, &resp)
	return resp, err
}

func (c *httpClient) QueryStats(ctx context.Context, req idl.GetUserRequest) (idl.GetUserResponse, error) {
	var resp idl.GetUserResponse
	path := "/querystats"
	b, _ := json.Marshal(req)
	var params map[string]interface{}
	json.Unmarshal(b, &params) //nolint:errcheck
	if len(params) > 0 {
		query := "?"
		for k, v := range params {
			query += fmt.Sprintf("%s=%v&", k, v)
		}
		path += query[:len(query)-1]
	}
	err := c.do(ctx, "GET", path, nil, &resp)
	return resp, err
}

func (c *httpClient) RemoveExpired(ctx context.Context, req idl.DeleteUserRequest) (idl.DeleteUserResponse, error) {
	var resp idl.DeleteUserResponse
	err := c.do(ctx, "DELETE", "/removeexpired", req, &resp)
	return resp, err
}

func (c *httpClient) EditProfile(ctx context.Context, req idl.UpdateUserRequest) (idl.UpdateUserResponse, error) {
	var resp idl.UpdateUserResponse
	err := c.do(ctx, "PUT", "/editprofile", req, &resp)
	return resp, err
}

func (c *httpClient) ModifyEmail(ctx context.Context, req idl.UpdateUserRequest) (idl.UpdateUserResponse, error) {
	var resp idl.UpdateUserResponse
	err := c.do(ctx, "PUT", "/modifyemail", req, &resp)
	return resp, err
}

func (c *httpClient) PatchStatus(ctx context.Context, req idl.UpdateUserRequest) (idl.UpdateUserResponse, error) {
	var resp idl.UpdateUserResponse
	err := c.do(ctx, "PUT", "/patchstatus", req, &resp)
	return resp, err
}


// ─────────────────────────── gRPC implementation ──────────────────────────────


