// Code generated by microgen. DO NOT EDIT.
package main

import (
	"net/http"
)

type generatedRouteEntry struct {
	Method  string
	Path    string
	Handler string
}

type generatedRuntime struct {
	routeEntries   []generatedRouteEntry
	httpRegistrars []func(*http.ServeMux)
}

func (rt generatedRuntime) registerRoutes(r *http.ServeMux) {
	for _, register := range rt.httpRegistrars {
		register(r)
	}
}

func generatedRouteEntries(rt generatedRuntime, customRoutes []generatedRouteEntry, withSwag bool, withSkill bool) []generatedRouteEntry {
	routes := []generatedRouteEntry{
		{Method: "GET", Path: "/health", Handler: "health"},
		{Method: "GET", Path: "/debug/routes", Handler: "debug"},
	}
	routes = append(routes, rt.routeEntries...)
	routes = append(routes, customRoutes...)
	if withSwag {
		routes = append(routes, generatedRouteEntry{Method: "GET", Path: "/swagger/", Handler: "swagger-ui"})
	}
	if withSkill {
		routes = append(routes, generatedRouteEntry{Method: "GET", Path: "/skill", Handler: "skill"})
	}

	return routes
}
