// Code generated by microgen. DO NOT EDIT.
package main

import (
	userserviceEndpoint "example.com/gen_idl_extend_check_missing/endpoint/userservice"
	userserviceSvc "example.com/gen_idl_extend_check_missing/service/userservice"
	kitlog "github.com/dreamsxin/go-kit/v2/log"
)

type generatedServices struct {
	userserviceSvc       userserviceSvc.UserService
	userserviceEndpoints userserviceEndpoint.UserServiceEndpoints
}

func initGeneratedServices(logger *kitlog.Logger) generatedServices {
	generated := generatedServices{}

	_ = logger
	generated.userserviceSvc = userserviceSvc.NewService(nil)
	generated.userserviceEndpoints = userserviceEndpoint.MakeServerEndpoints(generated.userserviceSvc, logger)

	return generated
}
