// Code generated by microgen. DO NOT EDIT.
// Re-generate with: microgen -idl <idl.go> -out <outdir> ...
//
// config.go 提供配置结构体定义和 YAML 配置文件加载逻辑。
// 配置文件默认路径为 config/config.yaml，可通过 -config 命令行参数覆盖。
package config

import (
	"fmt"
	"os"
	"time"

	"gopkg.in/yaml.v3"
)

// ─────────────────────────── 顶层配置 ───────────────────────────

// Config 聚合所有子配置
type Config struct {
	Server     ServerConfig     `yaml:"server"`
	Logging    LoggingConfig    `yaml:"logging"`
	Middleware  MiddlewareConfig `yaml:"middleware"`
	Debug       DebugConfig      `yaml:"debug"`
}

// ─────────────────────────── Server ───────────────────────────

// ServerConfig HTTP / gRPC 监听地址及超时配置
type ServerConfig struct {
	HTTPAddr                string        `yaml:"http_addr"`
	GRPCAddr                string        `yaml:"grpc_addr"`
	ReadTimeout             time.Duration `yaml:"read_timeout"`
	WriteTimeout            time.Duration `yaml:"write_timeout"`
	GracefulShutdownTimeout time.Duration `yaml:"graceful_shutdown_timeout"`
}

// ─────────────────────────── Logging ───────────────────────────

// LoggingConfig 日志配置
type LoggingConfig struct {
	Level  string `yaml:"level"`
	Format string `yaml:"format"`
}

// ─────────────────────────── Middleware ───────────────────────────

// MiddlewareConfig 中间件开关配置
type MiddlewareConfig struct {
	CircuitBreaker CircuitBreakerConfig `yaml:"circuit_breaker"`
	RateLimit      RateLimitConfig      `yaml:"rate_limit"`
	Retry          RetryConfig          `yaml:"retry"`
}

// CircuitBreakerConfig 熔断器配置
type CircuitBreakerConfig struct {
	Enabled          bool          `yaml:"enabled"`
	FailureThreshold int           `yaml:"failure_threshold"`
	Timeout          time.Duration `yaml:"timeout"`
}

// RateLimitConfig 限流配置
type RateLimitConfig struct {
	Enabled           bool    `yaml:"enabled"`
	RequestsPerSecond float64 `yaml:"requests_per_second"`
}

// RetryConfig 重试配置
type RetryConfig struct {
	Enabled     bool          `yaml:"enabled"`
	MaxAttempts int           `yaml:"max_attempts"`
	Backoff     time.Duration `yaml:"backoff"`
}

// ─────────────────────────── Debug ───────────────────────────

// DebugConfig 调试端点配置
type DebugConfig struct {
	// RoutesEnabled 控制 /debug/routes 端点是否可访问（生产环境建议关闭）
	RoutesEnabled bool `yaml:"routes_enabled"`
	// PrintRoutes 控制启动时是否在日志中打印路由表
	PrintRoutes   bool `yaml:"print_routes"`
}

// ─────────────────────────── 默认值 ───────────────────────────

// Default 返回内置默认配置，与 config.yaml 的默认内容保持一致。
func Default() *Config {
	return &Config{
		Server: ServerConfig{
			HTTPAddr:                ":8080",
			GRPCAddr:                ":8081",
			ReadTimeout:             15 * time.Second,
			WriteTimeout:            15 * time.Second,
			GracefulShutdownTimeout: 30 * time.Second,
		},
		Logging: LoggingConfig{
			Level:  "info",
			Format: "json",
		},
		Middleware: MiddlewareConfig{
			CircuitBreaker: CircuitBreakerConfig{
				Enabled:          true,
				FailureThreshold: 5,
				Timeout:          60 * time.Second,
			},
			RateLimit: RateLimitConfig{
				Enabled:           true,
				RequestsPerSecond: 100,
			},
			Retry: RetryConfig{
				Enabled:     true,
				MaxAttempts: 3,
				Backoff:     2 * time.Second,
			},
		},
		Debug: DebugConfig{
			RoutesEnabled: true,
			PrintRoutes:   true,
		},
	}
}

// ─────────────────────────── 加载函数 ───────────────────────────

// Load 从 YAML 文件加载配置。
//
//   - 若文件不存在，返回内置默认配置（不报错）。
//   - 若文件存在但解析失败，返回 error。
//   - YAML 中未填写的字段保持 Default() 中的值（merge 语义）。
func Load(path string) (*Config, error) {
	cfg := Default()

	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return cfg, nil
		}
		return nil, fmt.Errorf("config: read %s: %w", path, err)
	}

	if err := yaml.Unmarshal(data, cfg); err != nil {
		return nil, fmt.Errorf("config: parse %s: %w", path, err)
	}

	return cfg, nil
}
