// Code generated by microgen. DO NOT EDIT.
//
// Package orderservicesdk is the client SDK for OrderService.
//
// Usage:
//
//	// HTTP
//	client := orderservicesdk.New("http://localhost:8080")
//	resp, err := client.PlaceOrder(ctx, idl.PlaceOrderRequest{...})
//
// 
package orderservicesdk

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"


	idl "example.com/gen_idl_extend_append"
)

// ─────────────────────────── Client interface ────────────────────────────────

// Client is the OrderService client interface.
// It mirrors the server-side Service interface exactly, so any code that
// works against the interface can be tested with a mock.
type Client interface {
	// PlaceOrder
	PlaceOrder(ctx context.Context, req idl.PlaceOrderRequest) (idl.PlaceOrderResponse, error)

}

// ─────────────────────────── HTTP Constructor ────────────────────────────────

// Option configures the HTTP client.
type Option func(*httpClient)

// WithTimeout sets the per-request HTTP timeout (default: 30s).
func WithTimeout(d time.Duration) Option {
	return func(c *httpClient) { c.timeout = d }
}

// WithHTTPClient replaces the default *http.Client.
func WithHTTPClient(hc *http.Client) Option {
	return func(c *httpClient) { c.http = hc }
}

// WithHeader adds a static header to every request (e.g. Authorization).
func WithHeader(key, value string) Option {
	return func(c *httpClient) { c.headers[key] = value }
}

// WithBearerToken is a shorthand for WithHeader("Authorization", "Bearer "+token).
func WithBearerToken(token string) Option {
	return WithHeader("Authorization", "Bearer "+token)
}

// WithRequestHook registers a function called before every request.
// Use it to inject dynamic headers (e.g. per-request auth tokens).
func WithRequestHook(fn func(r *http.Request)) Option {
	return func(c *httpClient) { c.hooks = append(c.hooks, fn) }
}

// New creates a OrderService HTTP client.
//
// baseURL is the server base URL, e.g. "http://localhost:8080".
func New(baseURL string, opts ...Option) Client {
	c := &httpClient{
		baseURL: baseURL,
		timeout: 30 * time.Second,
		headers: make(map[string]string),
	}
	for _, o := range opts {
		o(c)
	}
	if c.http == nil {
		c.http = &http.Client{Timeout: c.timeout}
	}
	return c
}

// ─────────────────────────── gRPC Constructor ────────────────────────────────



// ─────────────────────────── HTTP implementation ──────────────────────────────

type httpClient struct {
	baseURL string
	timeout time.Duration
	http    *http.Client
	headers map[string]string
	hooks   []func(*http.Request)
}

// apiError is returned when the server responds with a non-2xx status.
type apiError struct {
	StatusCode int
	Body       string
}

func (e *apiError) Error() string {
	return fmt.Sprintf("orderservicesdk: server returned %d: %s", e.StatusCode, e.Body)
}

func (c *httpClient) do(ctx context.Context, method, path string, reqBody, respBody interface{}) error {
	var bodyReader io.Reader
	if reqBody != nil {
		b, err := json.Marshal(reqBody)
		if err != nil {
			return fmt.Errorf("orderservicesdk: marshal request: %w", err)
		}
		bodyReader = bytes.NewReader(b)
	}

	req, err := http.NewRequestWithContext(ctx, method, c.baseURL+path, bodyReader)
	if err != nil {
		return fmt.Errorf("orderservicesdk: build request: %w", err)
	}
	if reqBody != nil {
		req.Header.Set("Content-Type", "application/json; charset=utf-8")
	}
	req.Header.Set("Accept", "application/json")
	for k, v := range c.headers {
		req.Header.Set(k, v)
	}
	for _, hook := range c.hooks {
		hook(req)
	}

	resp, err := c.http.Do(req)
	if err != nil {
		return fmt.Errorf("orderservicesdk: send request: %w", err)
	}
	defer resp.Body.Close()

	raw, _ := io.ReadAll(resp.Body)
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return &apiError{StatusCode: resp.StatusCode, Body: string(raw)}
	}

	if respBody != nil {
		if err := json.Unmarshal(raw, respBody); err != nil {
			return fmt.Errorf("orderservicesdk: decode response: %w", err)
		}
	}
	return nil
}


func (c *httpClient) PlaceOrder(ctx context.Context, req idl.PlaceOrderRequest) (idl.PlaceOrderResponse, error) {
	var resp idl.PlaceOrderResponse
	err := c.do(ctx, "POST", "/placeorder", req, &resp)
	return resp, err
}


// ─────────────────────────── gRPC implementation ──────────────────────────────


