// Code generated by microgen. DO NOT EDIT.
package main

import (
	"github.com/gorilla/mux"
	userserviceTransport "example.com/gen_idl_prefixed_runtime/transport/userservice"
)

func (g generatedServices) generatedRuntime() generatedRuntime {
	rt := generatedRuntime{
		routeEntries: []generatedRouteEntry{
			{Method: "POST", Path: "/api/runtime/userservice/createuser", Handler: "CreateUser"},
			{Method: "GET", Path: "/api/runtime/userservice/getuser", Handler: "GetUser"},
			{Method: "GET", Path: "/api/runtime/userservice/listusers", Handler: "ListUsers"},
			{Method: "DELETE", Path: "/api/runtime/userservice/deleteuser", Handler: "DeleteUser"},
			{Method: "PUT", Path: "/api/runtime/userservice/updateuser", Handler: "UpdateUser"},
			{Method: "GET", Path: "/api/runtime/userservice/findbyemail", Handler: "FindByEmail"},
			{Method: "GET", Path: "/api/runtime/userservice/searchusers", Handler: "SearchUsers"},
			{Method: "GET", Path: "/api/runtime/userservice/querystats", Handler: "QueryStats"},
			{Method: "DELETE", Path: "/api/runtime/userservice/removeexpired", Handler: "RemoveExpired"},
			{Method: "PUT", Path: "/api/runtime/userservice/editprofile", Handler: "EditProfile"},
			{Method: "PUT", Path: "/api/runtime/userservice/modifyemail", Handler: "ModifyEmail"},
			{Method: "PUT", Path: "/api/runtime/userservice/patchstatus", Handler: "PatchStatus"},
		},
		httpRegistrars: []func(*mux.Router){
			func(router *mux.Router) {
				userserviceTransport.RegisterHTTPRoutes(router, g.userserviceEndpoints, "/api/runtime/userservice")
			},
		},
	}
	return rt
}
